-- Bangladesh division/district/upazila/postcode reference data, for the checkout's
-- postcode-to-address auto-fill. Source: https://github.com/bayeziddev/bangladesh-geocode
-- (public domain administrative reference data — division/district/upazila names
-- and 1996-vintage lat/lon centroids, plus the BD postal service's postcode-to-thana
-- table). Read-only reference tables — nothing here is ever written by the app itself.

CREATE TABLE IF NOT EXISTS bd_divisions (
  id      INTEGER PRIMARY KEY,
  name    TEXT NOT NULL,
  bn_name TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS bd_districts (
  id          INTEGER PRIMARY KEY,
  division_id INTEGER NOT NULL REFERENCES bd_divisions(id),
  name        TEXT NOT NULL,
  bn_name     TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_bd_districts_division ON bd_districts(division_id);

CREATE TABLE IF NOT EXISTS bd_upazilas (
  id          INTEGER PRIMARY KEY,
  district_id INTEGER NOT NULL REFERENCES bd_districts(id),
  name        TEXT NOT NULL,
  bn_name     TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_bd_upazilas_district ON bd_upazilas(district_id);

-- One row per postcode (a postcode can map to more than one thana/suboffice in the
-- source data; only the first is kept — good enough for a helpful auto-fill, and the
-- customer's own picked district/upazila always wins over this if they differ).
CREATE TABLE IF NOT EXISTS bd_postcodes (
  postcode      TEXT PRIMARY KEY,
  division_name TEXT NOT NULL,
  district_name TEXT NOT NULL,
  thana_name    TEXT NOT NULL
);

INSERT INTO bd_divisions (id, name, bn_name) VALUES
  (1, 'Chattagram', 'চট্টগ্রাম'),
  (2, 'Rajshahi', 'রাজশাহী'),
  (3, 'Khulna', 'খুলনা'),
  (4, 'Barisal', 'বরিশাল'),
  (5, 'Sylhet', 'সিলেট'),
  (6, 'Dhaka', 'ঢাকা'),
  (7, 'Rangpur', 'রংপুর'),
  (8, 'Mymensingh', 'ময়মনসিংহ');

INSERT INTO bd_districts (id, division_id, name, bn_name) VALUES
  (1, 1, 'Comilla', 'কুমিল্লা'),
  (2, 1, 'Feni', 'ফেনী'),
  (3, 1, 'Brahmanbaria', 'ব্রাহ্মণবাড়িয়া'),
  (4, 1, 'Rangamati', 'রাঙ্গামাটি'),
  (5, 1, 'Noakhali', 'নোয়াখালী'),
  (6, 1, 'Chandpur', 'চাঁদপুর'),
  (7, 1, 'Lakshmipur', 'লক্ষ্মীপুর'),
  (8, 1, 'Chattogram', 'চট্টগ্রাম'),
  (9, 1, 'Coxsbazar', 'কক্সবাজার'),
  (10, 1, 'Khagrachhari', 'খাগড়াছড়ি'),
  (11, 1, 'Bandarban', 'বান্দরবান'),
  (12, 2, 'Sirajganj', 'সিরাজগঞ্জ'),
  (13, 2, 'Pabna', 'পাবনা'),
  (14, 2, 'Bogura', 'বগুড়া'),
  (15, 2, 'Rajshahi', 'রাজশাহী'),
  (16, 2, 'Natore', 'নাটোর'),
  (17, 2, 'Joypurhat', 'জয়পুরহাট'),
  (18, 2, 'Chapainawabganj', 'চাঁপাইনবাবগঞ্জ'),
  (19, 2, 'Naogaon', 'নওগাঁ'),
  (20, 3, 'Jashore', 'যশোর'),
  (21, 3, 'Satkhira', 'সাতক্ষীরা'),
  (22, 3, 'Meherpur', 'মেহেরপুর'),
  (23, 3, 'Narail', 'নড়াইল'),
  (24, 3, 'Chuadanga', 'চুয়াডাঙ্গা'),
  (25, 3, 'Kushtia', 'কুষ্টিয়া'),
  (26, 3, 'Magura', 'মাগুরা'),
  (27, 3, 'Khulna', 'খুলনা'),
  (28, 3, 'Bagerhat', 'বাগেরহাট'),
  (29, 3, 'Jhenaidah', 'ঝিনাইদহ'),
  (30, 4, 'Jhalakathi', 'ঝালকাঠি'),
  (31, 4, 'Patuakhali', 'পটুয়াখালী'),
  (32, 4, 'Pirojpur', 'পিরোজপুর'),
  (33, 4, 'Barisal', 'বরিশাল'),
  (34, 4, 'Bhola', 'ভোলা'),
  (35, 4, 'Barguna', 'বরগুনা'),
  (36, 5, 'Sylhet', 'সিলেট'),
  (37, 5, 'Moulvibazar', 'মৌলভীবাজার'),
  (38, 5, 'Habiganj', 'হবিগঞ্জ'),
  (39, 5, 'Sunamganj', 'সুনামগঞ্জ'),
  (40, 6, 'Narsingdi', 'নরসিংদী'),
  (41, 6, 'Gazipur', 'গাজীপুর'),
  (42, 6, 'Shariatpur', 'শরীয়তপুর'),
  (43, 6, 'Narayanganj', 'নারায়ণগঞ্জ'),
  (44, 6, 'Tangail', 'টাঙ্গাইল'),
  (45, 6, 'Kishoreganj', 'কিশোরগঞ্জ'),
  (46, 6, 'Manikganj', 'মানিকগঞ্জ'),
  (47, 6, 'Dhaka', 'ঢাকা'),
  (48, 6, 'Munshiganj', 'মুন্সিগঞ্জ'),
  (49, 6, 'Rajbari', 'রাজবাড়ী'),
  (50, 6, 'Madaripur', 'মাদারীপুর'),
  (51, 6, 'Gopalganj', 'গোপালগঞ্জ'),
  (52, 6, 'Faridpur', 'ফরিদপুর'),
  (53, 7, 'Panchagarh', 'পঞ্চগড়'),
  (54, 7, 'Dinajpur', 'দিনাজপুর'),
  (55, 7, 'Lalmonirhat', 'লালমনিরহাট'),
  (56, 7, 'Nilphamari', 'নীলফামারী'),
  (57, 7, 'Gaibandha', 'গাইবান্ধা'),
  (58, 7, 'Thakurgaon', 'ঠাকুরগাঁও'),
  (59, 7, 'Rangpur', 'রংপুর'),
  (60, 7, 'Kurigram', 'কুড়িগ্রাম'),
  (61, 8, 'Sherpur', 'শেরপুর'),
  (62, 8, 'Mymensingh', 'ময়মনসিংহ'),
  (63, 8, 'Jamalpur', 'জামালপুর'),
  (64, 8, 'Netrokona', 'নেত্রকোণা');

INSERT INTO bd_upazilas (id, district_id, name, bn_name) VALUES
  (1, 1, 'Debidwar', 'দেবিদ্বার'),
  (2, 1, 'Barura', 'বরুড়া'),
  (3, 1, 'Brahmanpara', 'ব্রাহ্মণপাড়া'),
  (4, 1, 'Chandina', 'চান্দিনা'),
  (5, 1, 'Chauddagram', 'চৌদ্দগ্রাম'),
  (6, 1, 'Daudkandi', 'দাউদকান্দি'),
  (7, 1, 'Homna', 'হোমনা'),
  (8, 1, 'Laksam', 'লাকসাম'),
  (9, 1, 'Muradnagar', 'মুরাদনগর'),
  (10, 1, 'Nangalkot', 'নাঙ্গলকোট'),
  (11, 1, 'Comilla Sadar', 'কুমিল্লা সদর'),
  (12, 1, 'Meghna', 'মেঘনা'),
  (13, 1, 'Monohargonj', 'মনোহরগঞ্জ'),
  (14, 1, 'Sadarsouth', 'সদর দক্ষিণ'),
  (15, 1, 'Titas', 'তিতাস'),
  (16, 1, 'Burichang', 'বুড়িচং'),
  (17, 1, 'Lalmai', 'লালমাই'),
  (18, 2, 'Chhagalnaiya', 'ছাগলনাইয়া'),
  (19, 2, 'Feni Sadar', 'ফেনী সদর'),
  (20, 2, 'Sonagazi', 'সোনাগাজী'),
  (21, 2, 'Fulgazi', 'ফুলগাজী'),
  (22, 2, 'Parshuram', 'পরশুরাম'),
  (23, 2, 'Daganbhuiyan', 'দাগনভূঞা'),
  (24, 3, 'Brahmanbaria Sadar', 'ব্রাহ্মণবাড়িয়া সদর'),
  (25, 3, 'Kasba', 'কসবা'),
  (26, 3, 'Nasirnagar', 'নাসিরনগর'),
  (27, 3, 'Sarail', 'সরাইল'),
  (28, 3, 'Ashuganj', 'আশুগঞ্জ'),
  (29, 3, 'Akhaura', 'আখাউড়া'),
  (30, 3, 'Nabinagar', 'নবীনগর'),
  (31, 3, 'Bancharampur', 'বাঞ্ছারামপুর'),
  (32, 3, 'Bijoynagar', 'বিজয়নগর'),
  (33, 4, 'Rangamati Sadar', 'রাঙ্গামাটি সদর'),
  (34, 4, 'Kaptai', 'কাপ্তাই'),
  (35, 4, 'Kawkhali', 'কাউখালী'),
  (36, 4, 'Baghaichari', 'বাঘাইছড়ি'),
  (37, 4, 'Barkal', 'বরকল'),
  (38, 4, 'Langadu', 'লংগদু'),
  (39, 4, 'Rajasthali', 'রাজস্থলী'),
  (40, 4, 'Belaichari', 'বিলাইছড়ি'),
  (41, 4, 'Juraichari', 'জুরাছড়ি'),
  (42, 4, 'Naniarchar', 'নানিয়ারচর'),
  (43, 5, 'Noakhali Sadar', 'নোয়াখালী সদর'),
  (44, 5, 'Companiganj', 'কোম্পানীগঞ্জ'),
  (45, 5, 'Begumganj', 'বেগমগঞ্জ'),
  (46, 5, 'Hatia', 'হাতিয়া'),
  (47, 5, 'Subarnachar', 'সুবর্ণচর'),
  (48, 5, 'Kabirhat', 'কবিরহাট'),
  (49, 5, 'Senbug', 'সেনবাগ'),
  (50, 5, 'Chatkhil', 'চাটখিল'),
  (51, 5, 'Sonaimori', 'সোনাইমুড়ী'),
  (52, 6, 'Haimchar', 'হাইমচর'),
  (53, 6, 'Kachua', 'কচুয়া'),
  (54, 6, 'Shahrasti', 'শাহরাস্তি'),
  (55, 6, 'Chandpur Sadar', 'চাঁদপুর সদর'),
  (56, 6, 'Matlab South', 'মতলব দক্ষিণ'),
  (57, 6, 'Hajiganj', 'হাজীগঞ্জ'),
  (58, 6, 'Matlab North', 'মতলব উত্তর'),
  (59, 6, 'Faridgonj', 'ফরিদগঞ্জ'),
  (60, 7, 'Lakshmipur Sadar', 'লক্ষ্মীপুর সদর'),
  (61, 7, 'Kamalnagar', 'কমলনগর'),
  (62, 7, 'Raipur', 'রায়পুর'),
  (63, 7, 'Ramgati', 'রামগতি'),
  (64, 7, 'Ramganj', 'রামগঞ্জ'),
  (65, 8, 'Rangunia', 'রাঙ্গুনিয়া'),
  (66, 8, 'Sitakunda', 'সীতাকুন্ড'),
  (67, 8, 'Mirsharai', 'মীরসরাই'),
  (68, 8, 'Patiya', 'পটিয়া'),
  (69, 8, 'Sandwip', 'সন্দ্বীপ'),
  (70, 8, 'Banshkhali', 'বাঁশখালী'),
  (71, 8, 'Boalkhali', 'বোয়ালখালী'),
  (72, 8, 'Anwara', 'আনোয়ারা'),
  (73, 8, 'Chandanaish', 'চন্দনাইশ'),
  (74, 8, 'Satkania', 'সাতকানিয়া'),
  (75, 8, 'Lohagara', 'লোহাগাড়া'),
  (76, 8, 'Hathazari', 'হাটহাজারী'),
  (77, 8, 'Fatikchhari', 'ফটিকছড়ি'),
  (78, 8, 'Raozan', 'রাউজান'),
  (79, 8, 'Karnafuli', 'কর্ণফুলী'),
  (80, 9, 'Coxsbazar Sadar', 'কক্সবাজার সদর'),
  (81, 9, 'Chakaria', 'চকরিয়া'),
  (82, 9, 'Kutubdia', 'কুতুবদিয়া'),
  (83, 9, 'Ukhiya', 'উখিয়া'),
  (84, 9, 'Moheshkhali', 'মহেশখালী'),
  (85, 9, 'Pekua', 'পেকুয়া'),
  (86, 9, 'Ramu', 'রামু'),
  (87, 9, 'Teknaf', 'টেকনাফ'),
  (88, 10, 'Khagrachhari Sadar', 'খাগড়াছড়ি সদর'),
  (89, 10, 'Dighinala', 'দিঘীনালা'),
  (90, 10, 'Panchari', 'পানছড়ি'),
  (91, 10, 'Laxmichhari', 'লক্ষীছড়ি'),
  (92, 10, 'Mohalchari', 'মহালছড়ি'),
  (93, 10, 'Manikchari', 'মানিকছড়ি'),
  (94, 10, 'Ramgarh', 'রামগড়'),
  (95, 10, 'Matiranga', 'মাটিরাঙ্গা'),
  (96, 10, 'Guimara', 'গুইমারা'),
  (97, 11, 'Bandarban Sadar', 'বান্দরবান সদর'),
  (98, 11, 'Alikadam', 'আলীকদম'),
  (99, 11, 'Naikhongchhari', 'নাইক্ষ্যংছড়ি'),
  (100, 11, 'Rowangchhari', 'রোয়াংছড়ি'),
  (101, 11, 'Lama', 'লামা'),
  (102, 11, 'Ruma', 'রুমা'),
  (103, 11, 'Thanchi', 'থানচি'),
  (104, 12, 'Belkuchi', 'বেলকুচি'),
  (105, 12, 'Chauhali', 'চৌহালি'),
  (106, 12, 'Kamarkhand', 'কামারখন্দ'),
  (107, 12, 'Kazipur', 'কাজীপুর'),
  (108, 12, 'Raigonj', 'রায়গঞ্জ'),
  (109, 12, 'Shahjadpur', 'শাহজাদপুর'),
  (110, 12, 'Sirajganj Sadar', 'সিরাজগঞ্জ সদর'),
  (111, 12, 'Tarash', 'তাড়াশ'),
  (112, 12, 'Ullapara', 'উল্লাপাড়া'),
  (113, 13, 'Sujanagar', 'সুজানগর'),
  (114, 13, 'Ishurdi', 'ঈশ্বরদী'),
  (115, 13, 'Bhangura', 'ভাঙ্গুড়া'),
  (116, 13, 'Pabna Sadar', 'পাবনা সদর'),
  (117, 13, 'Bera', 'বেড়া'),
  (118, 13, 'Atghoria', 'আটঘরিয়া'),
  (119, 13, 'Chatmohar', 'চাটমোহর'),
  (120, 13, 'Santhia', 'সাঁথিয়া'),
  (121, 13, 'Faridpur', 'ফরিদপুর'),
  (122, 14, 'Kahaloo', 'কাহালু'),
  (123, 14, 'Bogra Sadar', 'বগুড়া সদর'),
  (124, 14, 'Shariakandi', 'সারিয়াকান্দি'),
  (125, 14, 'Shajahanpur', 'শাজাহানপুর'),
  (126, 14, 'Dupchanchia', 'দুপচাচিঁয়া'),
  (127, 14, 'Adamdighi', 'আদমদিঘি'),
  (128, 14, 'Nondigram', 'নন্দিগ্রাম'),
  (129, 14, 'Sonatala', 'সোনাতলা'),
  (130, 14, 'Dhunot', 'ধুনট'),
  (131, 14, 'Gabtali', 'গাবতলী'),
  (132, 14, 'Sherpur', 'শেরপুর'),
  (133, 14, 'Shibganj', 'শিবগঞ্জ'),
  (134, 15, 'Paba', 'পবা'),
  (135, 15, 'Durgapur', 'দুর্গাপুর'),
  (136, 15, 'Mohonpur', 'মোহনপুর'),
  (137, 15, 'Charghat', 'চারঘাট'),
  (138, 15, 'Puthia', 'পুঠিয়া'),
  (139, 15, 'Bagha', 'বাঘা'),
  (140, 15, 'Godagari', 'গোদাগাড়ী'),
  (141, 15, 'Tanore', 'তানোর'),
  (142, 15, 'Bagmara', 'বাগমারা'),
  (143, 16, 'Natore Sadar', 'নাটোর সদর'),
  (144, 16, 'Singra', 'সিংড়া'),
  (145, 16, 'Baraigram', 'বড়াইগ্রাম'),
  (146, 16, 'Bagatipara', 'বাগাতিপাড়া'),
  (147, 16, 'Lalpur', 'লালপুর'),
  (148, 16, 'Gurudaspur', 'গুরুদাসপুর'),
  (149, 16, 'Naldanga', 'নলডাঙ্গা'),
  (150, 17, 'Akkelpur', 'আক্কেলপুর'),
  (151, 17, 'Kalai', 'কালাই'),
  (152, 17, 'Khetlal', 'ক্ষেতলাল'),
  (153, 17, 'Panchbibi', 'পাঁচবিবি'),
  (154, 17, 'Joypurhat Sadar', 'জয়পুরহাট সদর'),
  (155, 18, 'Chapainawabganj Sadar', 'চাঁপাইনবাবগঞ্জ সদর'),
  (156, 18, 'Gomostapur', 'গোমস্তাপুর'),
  (157, 18, 'Nachol', 'নাচোল'),
  (158, 18, 'Bholahat', 'ভোলাহাট'),
  (159, 18, 'Shibganj', 'শিবগঞ্জ'),
  (160, 19, 'Mohadevpur', 'মহাদেবপুর'),
  (161, 19, 'Badalgachi', 'বদলগাছী'),
  (162, 19, 'Patnitala', 'পত্নিতলা'),
  (163, 19, 'Dhamoirhat', 'ধামইরহাট'),
  (164, 19, 'Niamatpur', 'নিয়ামতপুর'),
  (165, 19, 'Manda', 'মান্দা'),
  (166, 19, 'Atrai', 'আত্রাই'),
  (167, 19, 'Raninagar', 'রাণীনগর'),
  (168, 19, 'Naogaon Sadar', 'নওগাঁ সদর'),
  (169, 19, 'Porsha', 'পোরশা'),
  (170, 19, 'Sapahar', 'সাপাহার'),
  (171, 20, 'Manirampur', 'মণিরামপুর'),
  (172, 20, 'Abhaynagar', 'অভয়নগর'),
  (173, 20, 'Bagherpara', 'বাঘারপাড়া'),
  (174, 20, 'Chougachha', 'চৌগাছা'),
  (175, 20, 'Jhikargacha', 'ঝিকরগাছা'),
  (176, 20, 'Keshabpur', 'কেশবপুর'),
  (177, 20, 'Jessore Sadar', 'যশোর সদর'),
  (178, 20, 'Sharsha', 'শার্শা'),
  (179, 21, 'Assasuni', 'আশাশুনি'),
  (180, 21, 'Debhata', 'দেবহাটা'),
  (181, 21, 'Kalaroa', 'কলারোয়া'),
  (182, 21, 'Satkhira Sadar', 'সাতক্ষীরা সদর'),
  (183, 21, 'Shyamnagar', 'শ্যামনগর'),
  (184, 21, 'Tala', 'তালা'),
  (185, 21, 'Kaliganj', 'কালিগঞ্জ'),
  (186, 22, 'Mujibnagar', 'মুজিবনগর'),
  (187, 22, 'Meherpur Sadar', 'মেহেরপুর সদর'),
  (188, 22, 'Gangni', 'গাংনী'),
  (189, 23, 'Narail Sadar', 'নড়াইল সদর'),
  (190, 23, 'Lohagara', 'লোহাগড়া'),
  (191, 23, 'Kalia', 'কালিয়া'),
  (192, 24, 'Chuadanga Sadar', 'চুয়াডাঙ্গা সদর'),
  (193, 24, 'Alamdanga', 'আলমডাঙ্গা'),
  (194, 24, 'Damurhuda', 'দামুড়হুদা'),
  (195, 24, 'Jibannagar', 'জীবননগর'),
  (196, 25, 'Kushtia Sadar', 'কুষ্টিয়া সদর'),
  (197, 25, 'Kumarkhali', 'কুমারখালী'),
  (198, 25, 'Khoksa', 'খোকসা'),
  (199, 25, 'Mirpur', 'মিরপুর'),
  (200, 25, 'Daulatpur', 'দৌলতপুর');

INSERT INTO bd_upazilas (id, district_id, name, bn_name) VALUES
  (201, 25, 'Bheramara', 'ভেড়ামারা'),
  (202, 26, 'Shalikha', 'শালিখা'),
  (203, 26, 'Sreepur', 'শ্রীপুর'),
  (204, 26, 'Magura Sadar', 'মাগুরা সদর'),
  (205, 26, 'Mohammadpur', 'মহম্মদপুর'),
  (206, 27, 'Paikgasa', 'পাইকগাছা'),
  (207, 27, 'Fultola', 'ফুলতলা'),
  (208, 27, 'Digholia', 'দিঘলিয়া'),
  (209, 27, 'Rupsha', 'রূপসা'),
  (210, 27, 'Terokhada', 'তেরখাদা'),
  (211, 27, 'Dumuria', 'ডুমুরিয়া'),
  (212, 27, 'Botiaghata', 'বটিয়াঘাটা'),
  (213, 27, 'Dakop', 'দাকোপ'),
  (214, 27, 'Koyra', 'কয়রা'),
  (215, 28, 'Fakirhat', 'ফকিরহাট'),
  (216, 28, 'Bagerhat Sadar', 'বাগেরহাট সদর'),
  (217, 28, 'Mollahat', 'মোল্লাহাট'),
  (218, 28, 'Sarankhola', 'শরণখোলা'),
  (219, 28, 'Rampal', 'রামপাল'),
  (220, 28, 'Morrelganj', 'মোড়েলগঞ্জ'),
  (221, 28, 'Kachua', 'কচুয়া'),
  (222, 28, 'Mongla', 'মোংলা'),
  (223, 28, 'Chitalmari', 'চিতলমারী'),
  (224, 29, 'Jhenaidah Sadar', 'ঝিনাইদহ সদর'),
  (225, 29, 'Shailkupa', 'শৈলকুপা'),
  (226, 29, 'Harinakundu', 'হরিণাকুন্ডু'),
  (227, 29, 'Kaliganj', 'কালীগঞ্জ'),
  (228, 29, 'Kotchandpur', 'কোটচাঁদপুর'),
  (229, 29, 'Moheshpur', 'মহেশপুর'),
  (230, 30, 'Jhalakathi Sadar', 'ঝালকাঠি সদর'),
  (231, 30, 'Kathalia', 'কাঠালিয়া'),
  (232, 30, 'Nalchity', 'নলছিটি'),
  (233, 30, 'Rajapur', 'রাজাপুর'),
  (234, 31, 'Bauphal', 'বাউফল'),
  (235, 31, 'Patuakhali Sadar', 'পটুয়াখালী সদর'),
  (236, 31, 'Dumki', 'দুমকি'),
  (237, 31, 'Dashmina', 'দশমিনা'),
  (238, 31, 'Kalapara', 'কলাপাড়া'),
  (239, 31, 'Mirzaganj', 'মির্জাগঞ্জ'),
  (240, 31, 'Galachipa', 'গলাচিপা'),
  (241, 31, 'Rangabali', 'রাঙ্গাবালী'),
  (242, 32, 'Pirojpur Sadar', 'পিরোজপুর সদর'),
  (243, 32, 'Nazirpur', 'নাজিরপুর'),
  (244, 32, 'Kawkhali', 'কাউখালী'),
  (245, 32, 'Zianagar', 'জিয়ানগর'),
  (246, 32, 'Bhandaria', 'ভান্ডারিয়া'),
  (247, 32, 'Mathbaria', 'মঠবাড়ীয়া'),
  (248, 32, 'Nesarabad', 'নেছারাবাদ'),
  (249, 33, 'Barisal Sadar', 'বরিশাল সদর'),
  (250, 33, 'Bakerganj', 'বাকেরগঞ্জ'),
  (251, 33, 'Babuganj', 'বাবুগঞ্জ'),
  (252, 33, 'Wazirpur', 'উজিরপুর'),
  (253, 33, 'Banaripara', 'বানারীপাড়া'),
  (254, 33, 'Gournadi', 'গৌরনদী'),
  (255, 33, 'Agailjhara', 'আগৈলঝাড়া'),
  (256, 33, 'Mehendiganj', 'মেহেন্দিগঞ্জ'),
  (257, 33, 'Muladi', 'মুলাদী'),
  (258, 33, 'Hizla', 'হিজলা'),
  (259, 34, 'Bhola Sadar', 'ভোলা সদর'),
  (260, 34, 'Borhan Sddin', 'বোরহান উদ্দিন'),
  (261, 34, 'Charfesson', 'চরফ্যাশন'),
  (262, 34, 'Doulatkhan', 'দৌলতখান'),
  (263, 34, 'Monpura', 'মনপুরা'),
  (264, 34, 'Tazumuddin', 'তজুমদ্দিন'),
  (265, 34, 'Lalmohan', 'লালমোহন'),
  (266, 35, 'Amtali', 'আমতলী'),
  (267, 35, 'Barguna Sadar', 'বরগুনা সদর'),
  (268, 35, 'Betagi', 'বেতাগী'),
  (269, 35, 'Bamna', 'বামনা'),
  (270, 35, 'Pathorghata', 'পাথরঘাটা'),
  (271, 35, 'Taltali', 'তালতলি'),
  (272, 36, 'Balaganj', 'বালাগঞ্জ'),
  (273, 36, 'Beanibazar', 'বিয়ানীবাজার'),
  (274, 36, 'Bishwanath', 'বিশ্বনাথ'),
  (275, 36, 'Companiganj', 'কোম্পানীগঞ্জ'),
  (276, 36, 'Fenchuganj', 'ফেঞ্চুগঞ্জ'),
  (277, 36, 'Golapganj', 'গোলাপগঞ্জ'),
  (278, 36, 'Gowainghat', 'গোয়াইনঘাট'),
  (279, 36, 'Jaintiapur', 'জৈন্তাপুর'),
  (280, 36, 'Kanaighat', 'কানাইঘাট'),
  (281, 36, 'Sylhet Sadar', 'সিলেট সদর'),
  (282, 36, 'Zakiganj', 'জকিগঞ্জ'),
  (283, 36, 'Dakshinsurma', 'দক্ষিণ সুরমা'),
  (284, 36, 'Osmaninagar', 'ওসমানী নগর'),
  (285, 37, 'Barlekha', 'বড়লেখা'),
  (286, 37, 'Kamolganj', 'কমলগঞ্জ'),
  (287, 37, 'Kulaura', 'কুলাউড়া'),
  (288, 37, 'Moulvibazar Sadar', 'মৌলভীবাজার সদর'),
  (289, 37, 'Rajnagar', 'রাজনগর'),
  (290, 37, 'Sreemangal', 'শ্রীমঙ্গল'),
  (291, 37, 'Juri', 'জুড়ী'),
  (292, 38, 'Nabiganj', 'নবীগঞ্জ'),
  (293, 38, 'Bahubal', 'বাহুবল'),
  (294, 38, 'Ajmiriganj', 'আজমিরীগঞ্জ'),
  (295, 38, 'Baniachong', 'বানিয়াচং'),
  (296, 38, 'Lakhai', 'লাখাই'),
  (297, 38, 'Chunarughat', 'চুনারুঘাট'),
  (298, 38, 'Habiganj Sadar', 'হবিগঞ্জ সদর'),
  (299, 38, 'Madhabpur', 'মাধবপুর'),
  (300, 39, 'Sunamganj Sadar', 'সুনামগঞ্জ সদর'),
  (301, 39, 'South Sunamganj', 'দক্ষিণ সুনামগঞ্জ'),
  (302, 39, 'Bishwambarpur', 'বিশ্বম্ভরপুর'),
  (303, 39, 'Chhatak', 'ছাতক'),
  (304, 39, 'Jagannathpur', 'জগন্নাথপুর'),
  (305, 39, 'Dowarabazar', 'দোয়ারাবাজার'),
  (306, 39, 'Tahirpur', 'তাহিরপুর'),
  (307, 39, 'Dharmapasha', 'ধর্মপাশা'),
  (308, 39, 'Jamalganj', 'জামালগঞ্জ'),
  (309, 39, 'Shalla', 'শাল্লা'),
  (310, 39, 'Derai', 'দিরাই'),
  (311, 40, 'Belabo', 'বেলাবো'),
  (312, 40, 'Monohardi', 'মনোহরদী'),
  (313, 40, 'Narsingdi Sadar', 'নরসিংদী সদর'),
  (314, 40, 'Palash', 'পলাশ'),
  (315, 40, 'Raipura', 'রায়পুরা'),
  (316, 40, 'Shibpur', 'শিবপুর'),
  (317, 41, 'Kaliganj', 'কালীগঞ্জ'),
  (318, 41, 'Kaliakair', 'কালিয়াকৈর'),
  (319, 41, 'Kapasia', 'কাপাসিয়া'),
  (320, 41, 'Gazipur Sadar', 'গাজীপুর সদর'),
  (321, 41, 'Sreepur', 'শ্রীপুর'),
  (322, 42, 'Shariatpur Sadar', 'শরিয়তপুর সদর'),
  (323, 42, 'Naria', 'নড়িয়া'),
  (324, 42, 'Zajira', 'জাজিরা'),
  (325, 42, 'Gosairhat', 'গোসাইরহাট'),
  (326, 42, 'Bhedarganj', 'ভেদরগঞ্জ'),
  (327, 42, 'Damudya', 'ডামুড্যা'),
  (328, 43, 'Araihazar', 'আড়াইহাজার'),
  (329, 43, 'Bandar', 'বন্দর'),
  (330, 43, 'Narayanganj Sadar', 'নারায়নগঞ্জ সদর'),
  (331, 43, 'Rupganj', 'রূপগঞ্জ'),
  (332, 43, 'Sonargaon', 'সোনারগাঁ'),
  (333, 44, 'Basail', 'বাসাইল'),
  (334, 44, 'Bhuapur', 'ভুয়াপুর'),
  (335, 44, 'Delduar', 'দেলদুয়ার'),
  (336, 44, 'Ghatail', 'ঘাটাইল'),
  (337, 44, 'Gopalpur', 'গোপালপুর'),
  (338, 44, 'Madhupur', 'মধুপুর'),
  (339, 44, 'Mirzapur', 'মির্জাপুর'),
  (340, 44, 'Nagarpur', 'নাগরপুর'),
  (341, 44, 'Sakhipur', 'সখিপুর'),
  (342, 44, 'Tangail Sadar', 'টাঙ্গাইল সদর'),
  (343, 44, 'Kalihati', 'কালিহাতী'),
  (344, 44, 'Dhanbari', 'ধনবাড়ী'),
  (345, 45, 'Itna', 'ইটনা'),
  (346, 45, 'Katiadi', 'কটিয়াদী'),
  (347, 45, 'Bhairab', 'ভৈরব'),
  (348, 45, 'Tarail', 'তাড়াইল'),
  (349, 45, 'Hossainpur', 'হোসেনপুর'),
  (350, 45, 'Pakundia', 'পাকুন্দিয়া'),
  (351, 45, 'Kuliarchar', 'কুলিয়ারচর'),
  (352, 45, 'Kishoreganj Sadar', 'কিশোরগঞ্জ সদর'),
  (353, 45, 'Karimgonj', 'করিমগঞ্জ'),
  (354, 45, 'Bajitpur', 'বাজিতপুর'),
  (355, 45, 'Austagram', 'অষ্টগ্রাম'),
  (356, 45, 'Mithamoin', 'মিঠামইন'),
  (357, 45, 'Nikli', 'নিকলী'),
  (358, 46, 'Harirampur', 'হরিরামপুর'),
  (359, 46, 'Saturia', 'সাটুরিয়া'),
  (360, 46, 'Manikganj Sadar', 'মানিকগঞ্জ সদর'),
  (361, 46, 'Gior', 'ঘিওর'),
  (362, 46, 'Shibaloy', 'শিবালয়'),
  (363, 46, 'Doulatpur', 'দৌলতপুর'),
  (364, 46, 'Singiar', 'সিংগাইর'),
  (365, 47, 'Savar', 'সাভার'),
  (366, 47, 'Dhamrai', 'ধামরাই'),
  (367, 47, 'Keraniganj', 'কেরাণীগঞ্জ'),
  (368, 47, 'Nawabganj', 'নবাবগঞ্জ'),
  (369, 47, 'Dohar', 'দোহার'),
  (370, 48, 'Munshiganj Sadar', 'মুন্সিগঞ্জ সদর'),
  (371, 48, 'Sreenagar', 'শ্রীনগর'),
  (372, 48, 'Sirajdikhan', 'সিরাজদিখান'),
  (373, 48, 'Louhajanj', 'লৌহজং'),
  (374, 48, 'Gajaria', 'গজারিয়া'),
  (375, 48, 'Tongibari', 'টংগীবাড়ি'),
  (376, 49, 'Rajbari Sadar', 'রাজবাড়ী সদর'),
  (377, 49, 'Goalanda', 'গোয়ালন্দ'),
  (378, 49, 'Pangsa', 'পাংশা'),
  (379, 49, 'Baliakandi', 'বালিয়াকান্দি'),
  (380, 49, 'Kalukhali', 'কালুখালী'),
  (381, 50, 'Madaripur Sadar', 'মাদারীপুর সদর'),
  (382, 50, 'Shibchar', 'শিবচর'),
  (383, 50, 'Kalkini', 'কালকিনি'),
  (384, 50, 'Rajoir', 'রাজৈর'),
  (385, 51, 'Gopalganj Sadar', 'গোপালগঞ্জ সদর'),
  (386, 51, 'Kashiani', 'কাশিয়ানী'),
  (387, 51, 'Tungipara', 'টুংগীপাড়া'),
  (388, 51, 'Kotalipara', 'কোটালীপাড়া'),
  (389, 51, 'Muksudpur', 'মুকসুদপুর'),
  (390, 52, 'Faridpur Sadar', 'ফরিদপুর সদর'),
  (391, 52, 'Alfadanga', 'আলফাডাঙ্গা'),
  (392, 52, 'Boalmari', 'বোয়ালমারী'),
  (393, 52, 'Sadarpur', 'সদরপুর'),
  (394, 52, 'Nagarkanda', 'নগরকান্দা'),
  (395, 52, 'Bhanga', 'ভাঙ্গা'),
  (396, 52, 'Charbhadrasan', 'চরভদ্রাসন'),
  (397, 52, 'Madhukhali', 'মধুখালী'),
  (398, 52, 'Saltha', 'সালথা'),
  (399, 53, 'Panchagarh Sadar', 'পঞ্চগড় সদর'),
  (400, 53, 'Debiganj', 'দেবীগঞ্জ');

INSERT INTO bd_upazilas (id, district_id, name, bn_name) VALUES
  (401, 53, 'Boda', 'বোদা'),
  (402, 53, 'Atwari', 'আটোয়ারী'),
  (403, 53, 'Tetulia', 'তেতুলিয়া'),
  (404, 54, 'Nawabganj', 'নবাবগঞ্জ'),
  (405, 54, 'Birganj', 'বীরগঞ্জ'),
  (406, 54, 'Ghoraghat', 'ঘোড়াঘাট'),
  (407, 54, 'Birampur', 'বিরামপুর'),
  (408, 54, 'Parbatipur', 'পার্বতীপুর'),
  (409, 54, 'Bochaganj', 'বোচাগঞ্জ'),
  (410, 54, 'Kaharol', 'কাহারোল'),
  (411, 54, 'Fulbari', 'ফুলবাড়ী'),
  (412, 54, 'Dinajpur Sadar', 'দিনাজপুর সদর'),
  (413, 54, 'Hakimpur', 'হাকিমপুর'),
  (414, 54, 'Khansama', 'খানসামা'),
  (415, 54, 'Birol', 'বিরল'),
  (416, 54, 'Chirirbandar', 'চিরিরবন্দর'),
  (417, 55, 'Lalmonirhat Sadar', 'লালমনিরহাট সদর'),
  (418, 55, 'Kaliganj', 'কালীগঞ্জ'),
  (419, 55, 'Hatibandha', 'হাতীবান্ধা'),
  (420, 55, 'Patgram', 'পাটগ্রাম'),
  (421, 55, 'Aditmari', 'আদিতমারী'),
  (422, 56, 'Syedpur', 'সৈয়দপুর'),
  (423, 56, 'Domar', 'ডোমার'),
  (424, 56, 'Dimla', 'ডিমলা'),
  (425, 56, 'Jaldhaka', 'জলঢাকা'),
  (426, 56, 'Kishorganj', 'কিশোরগঞ্জ'),
  (427, 56, 'Nilphamari Sadar', 'নীলফামারী সদর'),
  (428, 57, 'Sadullapur', 'সাদুল্লাপুর'),
  (429, 57, 'Gaibandha Sadar', 'গাইবান্ধা সদর'),
  (430, 57, 'Palashbari', 'পলাশবাড়ী'),
  (431, 57, 'Saghata', 'সাঘাটা'),
  (432, 57, 'Gobindaganj', 'গোবিন্দগঞ্জ'),
  (433, 57, 'Sundarganj', 'সুন্দরগঞ্জ'),
  (434, 57, 'Phulchari', 'ফুলছড়ি'),
  (435, 58, 'Thakurgaon Sadar', 'ঠাকুরগাঁও সদর'),
  (436, 58, 'Pirganj', 'পীরগঞ্জ'),
  (437, 58, 'Ranisankail', 'রাণীশংকৈল'),
  (438, 58, 'Haripur', 'হরিপুর'),
  (439, 58, 'Baliadangi', 'বালিয়াডাঙ্গী'),
  (440, 59, 'Rangpur Sadar', 'রংপুর সদর'),
  (441, 59, 'Gangachara', 'গংগাচড়া'),
  (442, 59, 'Taragonj', 'তারাগঞ্জ'),
  (443, 59, 'Badargonj', 'বদরগঞ্জ'),
  (444, 59, 'Mithapukur', 'মিঠাপুকুর'),
  (445, 59, 'Pirgonj', 'পীরগঞ্জ'),
  (446, 59, 'Kaunia', 'কাউনিয়া'),
  (447, 59, 'Pirgacha', 'পীরগাছা'),
  (448, 60, 'Kurigram Sadar', 'কুড়িগ্রাম সদর'),
  (449, 60, 'Nageshwari', 'নাগেশ্বরী'),
  (450, 60, 'Bhurungamari', 'ভুরুঙ্গামারী'),
  (451, 60, 'Phulbari', 'ফুলবাড়ী'),
  (452, 60, 'Rajarhat', 'রাজারহাট'),
  (453, 60, 'Ulipur', 'উলিপুর'),
  (454, 60, 'Chilmari', 'চিলমারী'),
  (455, 60, 'Rowmari', 'রৌমারী'),
  (456, 60, 'Charrajibpur', 'চর রাজিবপুর'),
  (457, 61, 'Sherpur Sadar', 'শেরপুর সদর'),
  (458, 61, 'Nalitabari', 'নালিতাবাড়ী'),
  (459, 61, 'Sreebordi', 'শ্রীবরদী'),
  (460, 61, 'Nokla', 'নকলা'),
  (461, 61, 'Jhenaigati', 'ঝিনাইগাতী'),
  (462, 62, 'Fulbaria', 'ফুলবাড়ীয়া'),
  (463, 62, 'Trishal', 'ত্রিশাল'),
  (464, 62, 'Bhaluka', 'ভালুকা'),
  (465, 62, 'Muktagacha', 'মুক্তাগাছা'),
  (466, 62, 'Mymensingh Sadar', 'ময়মনসিংহ সদর'),
  (467, 62, 'Dhobaura', 'ধোবাউড়া'),
  (468, 62, 'Phulpur', 'ফুলপুর'),
  (469, 62, 'Haluaghat', 'হালুয়াঘাট'),
  (470, 62, 'Gouripur', 'গৌরীপুর'),
  (471, 62, 'Gafargaon', 'গফরগাঁও'),
  (472, 62, 'Iswarganj', 'ঈশ্বরগঞ্জ'),
  (473, 62, 'Nandail', 'নান্দাইল'),
  (474, 62, 'Tarakanda', 'তারাকান্দা'),
  (475, 63, 'Jamalpur Sadar', 'জামালপুর সদর'),
  (476, 63, 'Melandah', 'মেলান্দহ'),
  (477, 63, 'Islampur', 'ইসলামপুর'),
  (478, 63, 'Dewangonj', 'দেওয়ানগঞ্জ'),
  (479, 63, 'Sarishabari', 'সরিষাবাড়ী'),
  (480, 63, 'Madarganj', 'মাদারগঞ্জ'),
  (481, 63, 'Bokshiganj', 'বকশীগঞ্জ'),
  (482, 64, 'Barhatta', 'বারহাট্টা'),
  (483, 64, 'Durgapur', 'দুর্গাপুর'),
  (484, 64, 'Kendua', 'কেন্দুয়া'),
  (485, 64, 'Atpara', 'আটপাড়া'),
  (486, 64, 'Madan', 'মদন'),
  (487, 64, 'Khaliajuri', 'খালিয়াজুরী'),
  (488, 64, 'Kalmakanda', 'কলমাকান্দা'),
  (489, 64, 'Mohongonj', 'মোহনগঞ্জ'),
  (490, 64, 'Purbadhala', 'পূর্বধলা'),
  (491, 64, 'Netrokona Sadar', 'নেত্রকোণা সদর'),
  (492, 9, 'Eidgaon', 'ঈদগাঁও'),
  (493, 39, 'Madhyanagar', 'মধ্যনগর'),
  (494, 50, 'Dasar', 'ডাসার');

INSERT INTO bd_postcodes (postcode, division_name, district_name, thana_name) VALUES
  ('1206', 'Dhaka', 'Dhaka', 'Dhaka'),
  ('1350', 'Dhaka', 'Dhaka', 'Dhamrai'),
  ('1209', 'Dhaka', 'Dhaka', 'Dhanmondi'),
  ('1213', 'Dhaka', 'Dhaka', 'Gulshan'),
  ('1212', 'Dhaka', 'Dhaka', 'Gulshan'),
  ('1236', 'Dhaka', 'Dhaka', 'Jatrabari'),
  ('1331', 'Dhaka', 'Dhaka', 'Joypara'),
  ('1332', 'Dhaka', 'Dhaka', 'Joypara'),
  ('1312', 'Dhaka', 'Dhaka', 'Keraniganj'),
  ('1311', 'Dhaka', 'Dhaka', 'Keraniganj'),
  ('1313', 'Dhaka', 'Dhaka', 'Keraniganj'),
  ('1310', 'Dhaka', 'Dhaka', 'Keraniganj'),
  ('1219', 'Dhaka', 'Dhaka', 'Khilgaon'),
  ('1229', 'Dhaka', 'Dhaka', 'Khilkhet'),
  ('1211', 'Dhaka', 'Dhaka', 'Lalbag'),
  ('1216', 'Dhaka', 'Dhaka', 'Mirpur'),
  ('1207', 'Dhaka', 'Dhaka', 'Mohammadpur'),
  ('1225', 'Dhaka', 'Dhaka', 'Mohammadpur'),
  ('1222', 'Dhaka', 'Dhaka', 'Motijheel'),
  ('1223', 'Dhaka', 'Dhaka', 'Motijheel'),
  ('1323', 'Dhaka', 'Dhaka', 'Nawabganj'),
  ('1325', 'Dhaka', 'Dhaka', 'Nawabganj'),
  ('1322', 'Dhaka', 'Dhaka', 'Nawabganj'),
  ('1321', 'Dhaka', 'Dhaka', 'Nawabganj'),
  ('1324', 'Dhaka', 'Dhaka', 'Nawabganj'),
  ('1320', 'Dhaka', 'Dhaka', 'Nawabganj'),
  ('1205', 'Dhaka', 'Dhaka', 'Kalabagan (Old New market)'),
  ('1000', 'Dhaka', 'Dhaka', 'Palton'),
  ('1217', 'Dhaka', 'Dhaka', 'Ramna'),
  ('1214', 'Dhaka', 'Dhaka', 'Sabujbag'),
  ('1348', 'Dhaka', 'Dhaka', 'Savar'),
  ('1341', 'Dhaka', 'Dhaka', 'Savar'),
  ('1349', 'Dhaka', 'Dhaka', 'Savar'),
  ('1342', 'Dhaka', 'Dhaka', 'Savar'),
  ('1346', 'Dhaka', 'Dhaka', 'Savar'),
  ('1347', 'Dhaka', 'Dhaka', 'Savar'),
  ('1340', 'Dhaka', 'Dhaka', 'Savar'),
  ('1344', 'Dhaka', 'Dhaka', 'Savar'),
  ('1343', 'Dhaka', 'Dhaka', 'Savar'),
  ('1345', 'Dhaka', 'Dhaka', 'Savar'),
  ('1100', 'Dhaka', 'Dhaka', 'Sutrapur'),
  ('1204', 'Dhaka', 'Dhaka', 'Sutrapur'),
  ('1203', 'Dhaka', 'Dhaka', 'Sutrapur'),
  ('1215', 'Dhaka', 'Dhaka', 'Tejgaon'),
  ('1208', 'Dhaka', 'Dhaka', 'Tejgaon Industrial Area'),
  ('1230', 'Dhaka', 'Dhaka', 'Uttara'),
  ('7870', 'Dhaka', 'Faridpur', 'Alfadanga'),
  ('7830', 'Dhaka', 'Faridpur', 'Bhanga'),
  ('7860', 'Dhaka', 'Faridpur', 'Boalmari'),
  ('7861', 'Dhaka', 'Faridpur', 'Boalmari'),
  ('7810', 'Dhaka', 'Faridpur', 'Charbhadrasan'),
  ('7802', 'Dhaka', 'Faridpur', 'Faridpur Sadar'),
  ('7803', 'Dhaka', 'Faridpur', 'Faridpur Sadar'),
  ('7800', 'Dhaka', 'Faridpur', 'Faridpur Sadar'),
  ('7801', 'Dhaka', 'Faridpur', 'Faridpur Sadar'),
  ('7851', 'Dhaka', 'Faridpur', 'Madukhali'),
  ('7850', 'Dhaka', 'Faridpur', 'Madukhali'),
  ('7840', 'Dhaka', 'Faridpur', 'Nagarkanda'),
  ('7841', 'Dhaka', 'Faridpur', 'Nagarkanda'),
  ('7822', 'Dhaka', 'Faridpur', 'Sadarpur'),
  ('7821', 'Dhaka', 'Faridpur', 'Sadarpur'),
  ('7820', 'Dhaka', 'Faridpur', 'Sadarpur'),
  ('7804', 'Dhaka', 'Faridpur', 'Shriangan'),
  ('1703', 'Dhaka', 'Gazipur', 'Gazipur Sadar'),
  ('1701', 'Dhaka', 'Gazipur', 'Gazipur Sadar'),
  ('1702', 'Dhaka', 'Gazipur', 'Gazipur Sadar'),
  ('1700', 'Dhaka', 'Gazipur', 'Gazipur Sadar'),
  ('1704', 'Dhaka', 'Gazipur', 'Gazipur Sadar'),
  ('1750', 'Dhaka', 'Gazipur', 'Kaliakaar'),
  ('1751', 'Dhaka', 'Gazipur', 'Kaliakaar'),
  ('1720', 'Dhaka', 'Gazipur', 'Kaliganj'),
  ('1721', 'Dhaka', 'Gazipur', 'Kaliganj'),
  ('1722', 'Dhaka', 'Gazipur', 'Kaliganj'),
  ('1723', 'Dhaka', 'Gazipur', 'Kaliganj'),
  ('1730', 'Dhaka', 'Gazipur', 'Kapashia'),
  ('1712', 'Dhaka', 'Gazipur', 'Monnunagar'),
  ('1710', 'Dhaka', 'Gazipur', 'Monnunagar'),
  ('1711', 'Dhaka', 'Gazipur', 'Turag'),
  ('1743', 'Dhaka', 'Gazipur', 'Sreepur'),
  ('1747', 'Dhaka', 'Gazipur', 'Sreepur'),
  ('1748', 'Dhaka', 'Gazipur', 'Sreepur'),
  ('1745', 'Dhaka', 'Gazipur', 'Sreepur'),
  ('1744', 'Dhaka', 'Gazipur', 'Sreepur'),
  ('1740', 'Dhaka', 'Gazipur', 'Sripur'),
  ('1741', 'Dhaka', 'Gazipur', 'Sripur'),
  ('1742', 'Dhaka', 'Gazipur', 'Sripur'),
  ('8102', 'Dhaka', 'Gopalganj', 'Gopalganj Sadar'),
  ('8013', 'Dhaka', 'Gopalganj', 'Gopalganj Sadar'),
  ('8100', 'Dhaka', 'Gopalganj', 'Gopalganj Sadar'),
  ('8101', 'Dhaka', 'Gopalganj', 'Gopalganj Sadar'),
  ('8133', 'Dhaka', 'Gopalganj', 'Kashiani'),
  ('8130', 'Dhaka', 'Gopalganj', 'Kashiani'),
  ('8131', 'Dhaka', 'Gopalganj', 'Kashiani'),
  ('8132', 'Dhaka', 'Gopalganj', 'Kashiani'),
  ('8110', 'Dhaka', 'Gopalganj', 'Kotalipara'),
  ('8141', 'Dhaka', 'Gopalganj', 'Maksudpur'),
  ('8142', 'Dhaka', 'Gopalganj', 'Maksudpur'),
  ('8140', 'Dhaka', 'Gopalganj', 'Muksudpur'),
  ('8121', 'Dhaka', 'Gopalganj', 'Tungipara'),
  ('8120', 'Dhaka', 'Gopalganj', 'Tungipara'),
  ('2336', 'Dhaka', 'Kishoreganj', 'Bajitpur'),
  ('2338', 'Dhaka', 'Kishoreganj', 'Kuliarchar'),
  ('2337', 'Dhaka', 'Kishoreganj', 'Bajitpur'),
  ('2350', 'Dhaka', 'Kishoreganj', 'Bhairob'),
  ('2320', 'Dhaka', 'Kishoreganj', 'Hossenpur'),
  ('2390', 'Dhaka', 'Kishoreganj', 'Itna'),
  ('2310', 'Dhaka', 'Kishoreganj', 'Karimganj'),
  ('2331', 'Dhaka', 'Kishoreganj', 'Katiadi'),
  ('2330', 'Dhaka', 'Kishoreganj', 'Katiadi'),
  ('2301', 'Dhaka', 'Kishoreganj', 'Kishoreganj Sadar'),
  ('2300', 'Dhaka', 'Kishoreganj', 'Kishoreganj Sadar'),
  ('2302', 'Dhaka', 'Kishoreganj', 'Kishoreganj Sadar'),
  ('2303', 'Dhaka', 'Kishoreganj', 'Kishoreganj Sadar'),
  ('2341', 'Dhaka', 'Kishoreganj', 'Kuliarchar'),
  ('2340', 'Dhaka', 'Kishoreganj', 'Kuliarchar'),
  ('2371', 'Dhaka', 'Kishoreganj', 'Mithamoin'),
  ('2370', 'Dhaka', 'Kishoreganj', 'Mithamoin'),
  ('2360', 'Dhaka', 'Kishoreganj', 'Nikli'),
  ('2380', 'Dhaka', 'Kishoreganj', 'Ostagram'),
  ('2326', 'Dhaka', 'Kishoreganj', 'Pakundia'),
  ('2316', 'Dhaka', 'Kishoreganj', 'Tarial'),
  ('7932', 'Dhaka', 'Madaripur', 'Barhamganj'),
  ('7930', 'Dhaka', 'Madaripur', 'Barhamganj'),
  ('7931', 'Dhaka', 'Madaripur', 'Barhamganj'),
  ('7933', 'Dhaka', 'Madaripur', 'Barhamganj'),
  ('7920', 'Dhaka', 'Madaripur', 'kalkini'),
  ('7921', 'Dhaka', 'Madaripur', 'kalkini'),
  ('7901', 'Dhaka', 'Madaripur', 'Madaripur Sadar'),
  ('7903', 'Dhaka', 'Madaripur', 'Madaripur Sadar'),
  ('7902', 'Dhaka', 'Madaripur', 'Madaripur Sadar'),
  ('7900', 'Dhaka', 'Madaripur', 'Madaripur Sadar'),
  ('7904', 'Dhaka', 'Madaripur', 'Madaripur Sadar'),
  ('7911', 'Dhaka', 'Madaripur', 'Rajoir'),
  ('7910', 'Dhaka', 'Madaripur', 'Rajoir'),
  ('1860', 'Dhaka', 'Manikganj', 'Doulatpur'),
  ('1840', 'Dhaka', 'Manikganj', 'Ghior'),
  ('1831', 'Dhaka', 'Manikganj', 'Lechhraganj'),
  ('1830', 'Dhaka', 'Manikganj', 'Lechhraganj'),
  ('1804', 'Dhaka', 'Manikganj', 'Manikganj Sadar'),
  ('1802', 'Dhaka', 'Manikganj', 'Manikganj Sadar'),
  ('1803', 'Dhaka', 'Manikganj', 'Manikganj Sadar'),
  ('1801', 'Dhaka', 'Manikganj', 'Manikganj Sadar'),
  ('1800', 'Dhaka', 'Manikganj', 'Manikganj Sadar'),
  ('1811', 'Dhaka', 'Manikganj', 'Saturia'),
  ('1810', 'Dhaka', 'Manikganj', 'Saturia'),
  ('1851', 'Dhaka', 'Manikganj', 'Shibloya'),
  ('1850', 'Dhaka', 'Manikganj', 'Shibloya'),
  ('1852', 'Dhaka', 'Manikganj', 'Shibloya'),
  ('1853', 'Dhaka', 'Manikganj', 'Shibloya'),
  ('1821', 'Dhaka', 'Manikganj', 'Singari'),
  ('1822', 'Dhaka', 'Manikganj', 'Singari'),
  ('1820', 'Dhaka', 'Manikganj', 'Singari'),
  ('1510', 'Dhaka', 'Munshiganj', 'Gajaria'),
  ('1511', 'Dhaka', 'Munshiganj', 'Gajaria'),
  ('1512', 'Dhaka', 'Munshiganj', 'Gajaria'),
  ('1334', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1534', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1532', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1333', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1533', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1531', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1530', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1335', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1535', 'Dhaka', 'Munshiganj', 'Lohajong'),
  ('1503', 'Dhaka', 'Munshiganj', 'Munshiganj Sadar'),
  ('1502', 'Dhaka', 'Munshiganj', 'Munshiganj Sadar'),
  ('1500', 'Dhaka', 'Munshiganj', 'Munshiganj Sadar'),
  ('1501', 'Dhaka', 'Munshiganj', 'Munshiganj Sadar'),
  ('1542', 'Dhaka', 'Munshiganj', 'Sirajdikhan'),
  ('1541', 'Dhaka', 'Munshiganj', 'Sirajdikhan'),
  ('1543', 'Dhaka', 'Munshiganj', 'Sirajdikhan'),
  ('1544', 'Dhaka', 'Munshiganj', 'Sirajdikhan'),
  ('1540', 'Dhaka', 'Munshiganj', 'Sirajdikhan'),
  ('1557', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1551', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1558', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1553', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1554', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1555', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1552', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1550', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1556', 'Dhaka', 'Munshiganj', 'Sreenagar'),
  ('1523', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1522', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1521', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1525', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1524', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1527', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1526', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1520', 'Dhaka', 'Munshiganj', 'Tangibari'),
  ('1450', 'Dhaka', 'Narayanganj', 'Araihazar'),
  ('1460', 'Dhaka', 'Narayanganj', 'Rupganj'),
  ('1451', 'Dhaka', 'Narayanganj', 'Araihazar'),
  ('1440', 'Dhaka', 'Narayanganj', 'Baidder Bazar'),
  ('1441', 'Dhaka', 'Narayanganj', 'Baidder Bazar'),
  ('1442', 'Dhaka', 'Narayanganj', 'Baidder Bazar'),
  ('1410', 'Dhaka', 'Narayanganj', 'Bandar'),
  ('1413', 'Dhaka', 'Narayanganj', 'Bandar'),
  ('1411', 'Dhaka', 'Narayanganj', 'Bandar'),
  ('1414', 'Dhaka', 'Narayanganj', 'Bandar');

INSERT INTO bd_postcodes (postcode, division_name, district_name, thana_name) VALUES
  ('1412', 'Dhaka', 'Narayanganj', 'Bandar'),
  ('1421', 'Dhaka', 'Narayanganj', 'Fatullah'),
  ('1420', 'Dhaka', 'Narayanganj', 'Fatullah'),
  ('1400', 'Dhaka', 'Narayanganj', 'Narayanganj Sadar'),
  ('1462', 'Dhaka', 'Narayanganj', 'Rupganj'),
  ('1461', 'Dhaka', 'Narayanganj', 'Rupganj'),
  ('1464', 'Dhaka', 'Narayanganj', 'Rupganj'),
  ('1463', 'Dhaka', 'Narayanganj', 'Rupganj'),
  ('1431', 'Dhaka', 'Narayanganj', 'Siddirganj'),
  ('1432', 'Dhaka', 'Narayanganj', 'Siddirganj'),
  ('1430', 'Dhaka', 'Narayanganj', 'Siddirganj'),
  ('1640', 'Dhaka', 'Narsingdi', 'Belabo'),
  ('1651', 'Dhaka', 'Narsingdi', 'Monohordi'),
  ('1652', 'Dhaka', 'Narsingdi', 'Monohordi'),
  ('1650', 'Dhaka', 'Narsingdi', 'Monohordi'),
  ('1605', 'Dhaka', 'Narsingdi', 'Narsingdi Sadar'),
  ('1604', 'Dhaka', 'Narsingdi', 'Madhabdi'),
  ('1602', 'Dhaka', 'Narsingdi', 'Narsingdi Sadar'),
  ('1600', 'Dhaka', 'Narsingdi', 'Narsingdi Sadar'),
  ('1603', 'Dhaka', 'Narsingdi', 'Narsingdi Sadar'),
  ('1601', 'Dhaka', 'Narsingdi', 'Narsingdi Sadar'),
  ('1612', 'Dhaka', 'Narsingdi', 'Palash'),
  ('1613', 'Dhaka', 'Narsingdi', 'Palash'),
  ('1611', 'Dhaka', 'Narsingdi', 'Palash'),
  ('1610', 'Dhaka', 'Narsingdi', 'Palash'),
  ('1631', 'Dhaka', 'Narsingdi', 'Raypura'),
  ('1632', 'Dhaka', 'Narsingdi', 'Raypura'),
  ('1630', 'Dhaka', 'Narsingdi', 'Raypura'),
  ('1620', 'Dhaka', 'Narsingdi', 'Shibpur'),
  ('7730', 'Dhaka', 'Rajbari', 'Baliakandi'),
  ('7731', 'Dhaka', 'Rajbari', 'Baliakandi'),
  ('7723', 'Dhaka', 'Rajbari', 'Pangsha'),
  ('7720', 'Dhaka', 'Rajbari', 'Pangsha'),
  ('7721', 'Dhaka', 'Rajbari', 'Pangsha'),
  ('7722', 'Dhaka', 'Rajbari', 'Pangsha'),
  ('7710', 'Dhaka', 'Rajbari', 'Rajbari Sadar'),
  ('7711', 'Dhaka', 'Rajbari', 'Rajbari Sadar'),
  ('7700', 'Dhaka', 'Rajbari', 'Rajbari Sadar'),
  ('8030', 'Dhaka', 'Shariatpur', 'Bhedorganj'),
  ('8040', 'Dhaka', 'Shariatpur', 'Damudhya'),
  ('8050', 'Dhaka', 'Shariatpur', 'Gosairhat'),
  ('8010', 'Dhaka', 'Shariatpur', 'Jajira'),
  ('8021', 'Dhaka', 'Shariatpur', 'Naria'),
  ('8022', 'Dhaka', 'Shariatpur', 'Naria'),
  ('8024', 'Dhaka', 'Shariatpur', 'Naria'),
  ('8020', 'Dhaka', 'Shariatpur', 'Naria'),
  ('8023', 'Dhaka', 'Shariatpur', 'Naria'),
  ('8001', 'Dhaka', 'Shariatpur', 'Shariatpur Sadar'),
  ('8002', 'Dhaka', 'Shariatpur', 'Shariatpur Sadar'),
  ('8000', 'Dhaka', 'Shariatpur', 'Shariatpur Sadar'),
  ('1920', 'Dhaka', 'Tangail', 'Basail'),
  ('1960', 'Dhaka', 'Tangail', 'Bhuapur'),
  ('1910', 'Dhaka', 'Tangail', 'Delduar'),
  ('1913', 'Dhaka', 'Tangail', 'Delduar'),
  ('1914', 'Dhaka', 'Tangail', 'Delduar'),
  ('1911', 'Dhaka', 'Tangail', 'Delduar'),
  ('1915', 'Dhaka', 'Tangail', 'Delduar'),
  ('1912', 'Dhaka', 'Tangail', 'Delduar'),
  ('1982', 'Dhaka', 'Tangail', 'Ghatail'),
  ('1983', 'Dhaka', 'Tangail', 'Ghatail'),
  ('1980', 'Dhaka', 'Tangail', 'Ghatail'),
  ('1984', 'Dhaka', 'Tangail', 'Ghatail'),
  ('1981', 'Dhaka', 'Tangail', 'Ghatail'),
  ('1990', 'Dhaka', 'Tangail', 'Gopalpur'),
  ('1992', 'Dhaka', 'Tangail', 'Gopalpur'),
  ('1991', 'Dhaka', 'Tangail', 'Gopalpur'),
  ('1973', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1974', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1970', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1977', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1976', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1972', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1975', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1971', 'Dhaka', 'Tangail', 'Kalihati'),
  ('1930', 'Dhaka', 'Tangail', 'Kashkaolia'),
  ('1997', 'Dhaka', 'Tangail', 'Madhupur'),
  ('1996', 'Dhaka', 'Tangail', 'Madhupur'),
  ('1941', 'Dhaka', 'Tangail', 'Mirzapur'),
  ('1944', 'Dhaka', 'Tangail', 'Mirzapur'),
  ('1942', 'Dhaka', 'Tangail', 'Mirzapur'),
  ('1940', 'Dhaka', 'Tangail', 'Mirzapur'),
  ('1945', 'Dhaka', 'Tangail', 'Mirzapur'),
  ('1943', 'Dhaka', 'Tangail', 'Mirzapur'),
  ('1937', 'Dhaka', 'Tangail', 'Nagarpur'),
  ('1936', 'Dhaka', 'Tangail', 'Nagarpur'),
  ('1938', 'Dhaka', 'Tangail', 'Nagarpur'),
  ('1951', 'Dhaka', 'Tangail', 'Sakhipur'),
  ('1950', 'Dhaka', 'Tangail', 'Sakhipur'),
  ('1901', 'Dhaka', 'Tangail', 'Tangail Sadar'),
  ('1903', 'Dhaka', 'Tangail', 'Tangail Sadar'),
  ('1904', 'Dhaka', 'Tangail', 'Tangail Sadar'),
  ('1902', 'Dhaka', 'Tangail', 'Tangail Sadar'),
  ('1900', 'Dhaka', 'Tangail', 'Tangail Sadar'),
  ('2140', 'Mymensingh', 'Sherpur', 'Bakshigonj'),
  ('2030', 'Mymensingh', 'Jamalpur', 'Dewangonj'),
  ('2032', 'Mymensingh', 'Jamalpur', 'Dewangonj'),
  ('2021', 'Mymensingh', 'Jamalpur', 'Islampur'),
  ('2022', 'Mymensingh', 'Jamalpur', 'Islampur'),
  ('2020', 'Mymensingh', 'Jamalpur', 'Islampur'),
  ('2000', 'Mymensingh', 'Jamalpur', 'Jamalpur'),
  ('2001', 'Mymensingh', 'Jamalpur', 'Jamalpur'),
  ('2002', 'Mymensingh', 'Jamalpur', 'Jamalpur'),
  ('2011', 'Mymensingh', 'Jamalpur', 'Melandah'),
  ('2013', 'Mymensingh', 'Jamalpur', 'Melandah'),
  ('2012', 'Mymensingh', 'Jamalpur', 'Melandah'),
  ('2010', 'Mymensingh', 'Jamalpur', 'Melandah'),
  ('2041', 'Mymensingh', 'Jamalpur', 'Madarganj'),
  ('2040', 'Mymensingh', 'Jamalpur', 'Madarganj'),
  ('2052', 'Mymensingh', 'Jamalpur', 'Sharishabari'),
  ('2051', 'Mymensingh', 'Jamalpur', 'Madarganj'),
  ('2053', 'Mymensingh', 'Jamalpur', 'Sharishabari'),
  ('2055', 'Mymensingh', 'Jamalpur', 'Sharishabari'),
  ('2054', 'Mymensingh', 'Jamalpur', 'Sharishabari'),
  ('2050', 'Mymensingh', 'Jamalpur', 'Sharishabari'),
  ('2240', 'Mymensingh', 'Mymensingh', 'Bhaluka'),
  ('2216', 'Mymensingh', 'Mymensingh', 'Fulbaria'),
  ('2234', 'Mymensingh', 'Mymensingh', 'Gaforgaon'),
  ('2230', 'Mymensingh', 'Mymensingh', 'Gaforgaon'),
  ('2233', 'Mymensingh', 'Mymensingh', 'Gaforgaon'),
  ('2231', 'Mymensingh', 'Mymensingh', 'Gaforgaon'),
  ('2232', 'Mymensingh', 'Mymensingh', 'Gaforgaon'),
  ('2270', 'Mymensingh', 'Mymensingh', 'Gouripur'),
  ('2271', 'Mymensingh', 'Mymensingh', 'Gouripur'),
  ('2261', 'Mymensingh', 'Mymensingh', 'Haluaghat'),
  ('2260', 'Mymensingh', 'Mymensingh', 'Haluaghat'),
  ('2262', 'Mymensingh', 'Mymensingh', 'Haluaghat'),
  ('2282', 'Mymensingh', 'Mymensingh', 'Isshwargonj'),
  ('2280', 'Mymensingh', 'Mymensingh', 'Isshwargonj'),
  ('2281', 'Mymensingh', 'Mymensingh', 'Isshwargonj'),
  ('2210', 'Mymensingh', 'Mymensingh', 'Muktagachha'),
  ('2202', 'Mymensingh', 'Mymensingh', 'Mymensingh Sadar'),
  ('2204', 'Mymensingh', 'Mymensingh', 'Mymensingh Sadar'),
  ('2201', 'Mymensingh', 'Mymensingh', 'Mymensingh Sadar'),
  ('2200', 'Mymensingh', 'Mymensingh', 'Mymensingh Sadar'),
  ('2205', 'Mymensingh', 'Mymensingh', 'Mymensingh Sadar'),
  ('2203', 'Mymensingh', 'Mymensingh', 'Mymensingh Sadar'),
  ('2291', 'Mymensingh', 'Mymensingh', 'Nandail'),
  ('2290', 'Mymensingh', 'Mymensingh', 'Nandail'),
  ('2251', 'Mymensingh', 'Mymensingh', 'Phulpur'),
  ('2250', 'Mymensingh', 'Mymensingh', 'Phulpur'),
  ('2252', 'Mymensingh', 'Mymensingh', 'Phulpur'),
  ('2221', 'Mymensingh', 'Mymensingh', 'Trishal'),
  ('2223', 'Mymensingh', 'Mymensingh', 'Trishal'),
  ('2222', 'Mymensingh', 'Mymensingh', 'Trishal'),
  ('2220', 'Mymensingh', 'Mymensingh', 'Trishal'),
  ('2420', 'Mymensingh', 'Netrakona', 'Susung Durgapur'),
  ('2470', 'Mymensingh', 'Netrakona', 'Atpara'),
  ('2440', 'Mymensingh', 'Netrakona', 'Barhatta'),
  ('2450', 'Mymensingh', 'Netrakona', 'Dharmapasha'),
  ('2416', 'Mymensingh', 'Netrakona', 'Dhobaura'),
  ('2417', 'Mymensingh', 'Netrakona', 'Dhobaura'),
  ('2430', 'Mymensingh', 'Netrakona', 'Kalmakanda'),
  ('2480', 'Mymensingh', 'Netrakona', 'Kendua'),
  ('2460', 'Mymensingh', 'Netrakona', 'Khaliajuri'),
  ('2462', 'Mymensingh', 'Netrakona', 'Khaliajuri'),
  ('2490', 'Mymensingh', 'Netrakona', 'Madan'),
  ('2456', 'Mymensingh', 'Netrakona', 'Moddhynagar'),
  ('2446', 'Mymensingh', 'Netrakona', 'Mohanganj'),
  ('2401', 'Mymensingh', 'Netrakona', 'Netrakona Sadar'),
  ('2400', 'Mymensingh', 'Netrakona', 'Netrakona Sadar'),
  ('2412', 'Mymensingh', 'Netrakona', 'Purbadhola'),
  ('2410', 'Mymensingh', 'Netrakona', 'Purbadhola'),
  ('2411', 'Mymensingh', 'Netrakona', 'Purbadhola'),
  ('2120', 'Mymensingh', 'Sherpur', 'Jhinaigati'),
  ('2151', 'Mymensingh', 'Sherpur', 'Nakla'),
  ('2150', 'Mymensingh', 'Sherpur', 'Nakla'),
  ('2111', 'Mymensingh', 'Sherpur', 'Nalitabari'),
  ('2110', 'Mymensingh', 'Sherpur', 'Nalitabari'),
  ('2100', 'Mymensingh', 'Sherpur', 'Sherpur Shadar'),
  ('2130', 'Mymensingh', 'Sherpur', 'Shribardi'),
  ('3360', 'Sylhet', 'Habiganj', 'Azmireeganj'),
  ('3310', 'Sylhet', 'Habiganj', 'Bahubal'),
  ('3350', 'Sylhet', 'Habiganj', 'Baniachang'),
  ('3351', 'Sylhet', 'Habiganj', 'Baniachang'),
  ('3352', 'Sylhet', 'Habiganj', 'Baniachang'),
  ('3321', 'Sylhet', 'Habiganj', 'Chunarughat'),
  ('3320', 'Sylhet', 'Habiganj', 'Chunarughat'),
  ('3322', 'Sylhet', 'Habiganj', 'Chunarughat'),
  ('3302', 'Sylhet', 'Habiganj', 'Habiganj Sadar'),
  ('3300', 'Sylhet', 'Habiganj', 'Habiganj Sadar'),
  ('3301', 'Sylhet', 'Habiganj', 'Habiganj Sadar'),
  ('3340', 'Sylhet', 'Habiganj', 'Kalauk'),
  ('3341', 'Sylhet', 'Habiganj', 'Kalauk'),
  ('3331', 'Sylhet', 'Habiganj', 'Madhabpur'),
  ('3330', 'Sylhet', 'Habiganj', 'Madhabpur'),
  ('3333', 'Sylhet', 'Habiganj', 'Madhabpur'),
  ('3332', 'Sylhet', 'Habiganj', 'Madhabpur'),
  ('3373', 'Sylhet', 'Habiganj', 'Nabiganj'),
  ('3372', 'Sylhet', 'Habiganj', 'Nabiganj'),
  ('3371', 'Sylhet', 'Habiganj', 'Nabiganj'),
  ('3374', 'Sylhet', 'Habiganj', 'Nabiganj'),
  ('3370', 'Sylhet', 'Habiganj', 'Nabiganj'),
  ('3250', 'Sylhet', 'Moulvibazar', 'Baralekha'),
  ('3252', 'Sylhet', 'Moulvibazar', 'Baralekha'),
  ('3251', 'Sylhet', 'Moulvibazar', 'Baralekha'),
  ('3253', 'Sylhet', 'Moulvibazar', 'Baralekha'),
  ('3220', 'Sylhet', 'Moulvibazar', 'Kamalganj'),
  ('3221', 'Sylhet', 'Moulvibazar', 'Kamalganj'),
  ('3224', 'Sylhet', 'Moulvibazar', 'Kamalganj'),
  ('3222', 'Sylhet', 'Moulvibazar', 'Kamalganj');

INSERT INTO bd_postcodes (postcode, division_name, district_name, thana_name) VALUES
  ('3223', 'Sylhet', 'Moulvibazar', 'Kamalganj'),
  ('3237', 'Sylhet', 'Moulvibazar', 'Kulaura'),
  ('3234', 'Sylhet', 'Moulvibazar', 'Kulaura'),
  ('3235', 'Sylhet', 'Moulvibazar', 'Kulaura'),
  ('3230', 'Sylhet', 'Moulvibazar', 'Kulaura'),
  ('3232', 'Sylhet', 'Moulvibazar', 'Kulaura'),
  ('3233', 'Sylhet', 'Moulvibazar', 'Kulaura'),
  ('3231', 'Sylhet', 'Moulvibazar', 'Kulaura'),
  ('3203', 'Sylhet', 'Moulvibazar', 'Moulvibazar Sadar'),
  ('3201', 'Sylhet', 'Moulvibazar', 'Moulvibazar Sadar'),
  ('3202', 'Sylhet', 'Moulvibazar', 'Moulvibazar Sadar'),
  ('3200', 'Sylhet', 'Moulvibazar', 'Moulvibazar Sadar'),
  ('3240', 'Sylhet', 'Moulvibazar', 'Rajnagar'),
  ('3212', 'Sylhet', 'Moulvibazar', 'Srimangal'),
  ('3213', 'Sylhet', 'Moulvibazar', 'Srimangal'),
  ('3211', 'Sylhet', 'Moulvibazar', 'Srimangal'),
  ('3214', 'Sylhet', 'Moulvibazar', 'Srimangal'),
  ('3210', 'Sylhet', 'Moulvibazar', 'Srimangal'),
  ('3010', 'Sylhet', 'Sunamganj', 'Bishamsarpur'),
  ('3080', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3081', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3082', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3893', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3083', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3084', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3088', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3087', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3085', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3086', 'Sylhet', 'Sunamganj', 'Chhatak'),
  ('3040', 'Sylhet', 'Sunamganj', 'Dhirai Chandpur'),
  ('3041', 'Sylhet', 'Sunamganj', 'Dhirai Chandpur'),
  ('3070', 'Sylhet', 'Sunamganj', 'Duara bazar'),
  ('3050', 'Sylhet', 'Sunamganj', 'Ghungiar'),
  ('3062', 'Sylhet', 'Sunamganj', 'Jagnnathpur'),
  ('3063', 'Sylhet', 'Sunamganj', 'Jagnnathpur'),
  ('3060', 'Sylhet', 'Sunamganj', 'Jagnnathpur'),
  ('3064', 'Sylhet', 'Sunamganj', 'Jagnnathpur'),
  ('3065', 'Sylhet', 'Sunamganj', 'Jagnnathpur'),
  ('3061', 'Sylhet', 'Sunamganj', 'Jagnnathpur'),
  ('3127', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3020', 'Sylhet', 'Sunamganj', 'Sachna'),
  ('3001', 'Sylhet', 'Sunamganj', 'Sunamganj Sadar'),
  ('3002', 'Sylhet', 'Sunamganj', 'Sunamganj Sadar'),
  ('3000', 'Sylhet', 'Sunamganj', 'Sunamganj Sadar'),
  ('3030', 'Sylhet', 'Sunamganj', 'Tahirpur'),
  ('3120', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3125', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3122', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3128', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3124', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3121', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3129', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3126', 'Sylhet', 'Sylhet', 'Balaganj'),
  ('3123', 'Sylhet', 'Sylhet', 'Balaganjgfhfghj'),
  ('3170', 'Sylhet', 'Sylhet', 'Bianibazar'),
  ('3175', 'Sylhet', 'Sylhet', 'Bianibazar'),
  ('3171', 'Sylhet', 'Sylhet', 'Bianibazar'),
  ('3173', 'Sylhet', 'Sylhet', 'Bianibazar'),
  ('3172', 'Sylhet', 'Sylhet', 'Bianibazar'),
  ('3174', 'Sylhet', 'Sylhet', 'Bianibazar'),
  ('3130', 'Sylhet', 'Sylhet', 'Bishwanath'),
  ('3131', 'Sylhet', 'Sylhet', 'Bishwanath'),
  ('3133', 'Sylhet', 'Sylhet', 'Bishwanath'),
  ('3132', 'Sylhet', 'Sylhet', 'Bishwanath'),
  ('3134', 'Sylhet', 'Sylhet', 'Bishwanath'),
  ('3116', 'Sylhet', 'Sylhet', 'Fenchuganj'),
  ('3117', 'Sylhet', 'Sylhet', 'Fenchuganj'),
  ('3152', 'Sylhet', 'Sylhet', 'Goainghat'),
  ('3150', 'Sylhet', 'Sylhet', 'Goainghat'),
  ('3151', 'Sylhet', 'Sylhet', 'Goainghat'),
  ('3164', 'Sylhet', 'Sylhet', 'Golapganj'),
  ('3165', 'Sylhet', 'Sylhet', 'Golapganj'),
  ('3162', 'Sylhet', 'Sylhet', 'Golapganj'),
  ('3161', 'Sylhet', 'Sylhet', 'Golapganj'),
  ('3160', 'Sylhet', 'Sylhet', 'Golapganj'),
  ('3163', 'Sylhet', 'Sylhet', 'Golapganj'),
  ('3156', 'Sylhet', 'Sylhet', 'Jaintapur'),
  ('3191', 'Sylhet', 'Sylhet', 'Jakiganj'),
  ('3190', 'Sylhet', 'Sylhet', 'Jakiganj'),
  ('3181', 'Sylhet', 'Sylhet', 'Kanaighat'),
  ('3183', 'Sylhet', 'Sylhet', 'Kanaighat'),
  ('3180', 'Sylhet', 'Sylhet', 'Kanaighat'),
  ('3182', 'Sylhet', 'Sylhet', 'Kanaighat'),
  ('3140', 'Sylhet', 'Sylhet', 'Kompanyganj'),
  ('3106', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3107', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3104', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3111', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3112', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3103', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3113', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3108', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3109', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3114', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3105', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3100', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3102', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3101', 'Sylhet', 'Sylhet', 'Sylhet Sadar'),
  ('3937', 'Chattogram', 'Feni', 'Sonagazi'),
  ('4650', 'Chattogram', 'Bandarban', 'Alikadam'),
  ('4660', 'Chattogram', 'Bandarban', 'Naikhong'),
  ('4610', 'Chattogram', 'Bandarban', 'Roanchhari'),
  ('4620', 'Chattogram', 'Bandarban', 'Ruma'),
  ('4641', 'Chattogram', 'Bandarban', 'Thanchi'),
  ('4630', 'Chattogram', 'Bandarban', 'Thanchi'),
  ('3450', 'Chattogram', 'Brahmanbaria', 'Akhaura'),
  ('3451', 'Chattogram', 'Brahmanbaria', 'Akhaura'),
  ('3452', 'Chattogram', 'Brahmanbaria', 'Akhaura'),
  ('3420', 'Chattogram', 'Brahmanbaria', 'Banchharampur'),
  ('3402', 'Chattogram', 'Brahmanbaria', 'Brahamanbaria Sadar'),
  ('3403', 'Chattogram', 'Brahmanbaria', 'Brahamanbaria Sadar'),
  ('3400', 'Chattogram', 'Brahmanbaria', 'Brahamanbaria Sadar'),
  ('3404', 'Chattogram', 'Brahmanbaria', 'Brahamanbaria Sadar'),
  ('3401', 'Chattogram', 'Brahmanbaria', 'Brahamanbaria Sadar'),
  ('3462', 'Chattogram', 'Brahmanbaria', 'Kasba'),
  ('3463', 'Chattogram', 'Brahmanbaria', 'Kasba'),
  ('3464', 'Chattogram', 'Brahmanbaria', 'Kasba'),
  ('3460', 'Chattogram', 'Brahmanbaria', 'Kasba'),
  ('3461', 'Chattogram', 'Brahmanbaria', 'Kasba'),
  ('3419', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3417', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3411', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3410', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3412', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3414', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3418', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3415', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3413', 'Chattogram', 'Brahmanbaria', 'Nabinagar'),
  ('3441', 'Chattogram', 'Brahmanbaria', 'Nasirnagar'),
  ('3440', 'Chattogram', 'Brahmanbaria', 'Nasirnagar'),
  ('3432', 'Chattogram', 'Brahmanbaria', 'Sarail'),
  ('3430', 'Chattogram', 'Brahmanbaria', 'Sarail'),
  ('3431', 'Chattogram', 'Brahmanbaria', 'Sarail'),
  ('3602', 'Chattogram', 'Chandpur', 'Chandpur Sadar'),
  ('3600', 'Chattogram', 'Chandpur', 'Chandpur Sadar'),
  ('3601', 'Chattogram', 'Chandpur', 'Chandpur Sadar'),
  ('3603', 'Chattogram', 'Chandpur', 'Chandpur Sadar'),
  ('3651', 'Chattogram', 'Chandpur', 'Faridganj'),
  ('3650', 'Chattogram', 'Chandpur', 'Faridganj'),
  ('3653', 'Chattogram', 'Chandpur', 'Faridganj'),
  ('3655', 'Chattogram', 'Chandpur', 'Faridganj'),
  ('3654', 'Chattogram', 'Chandpur', 'Faridganj'),
  ('3652', 'Chattogram', 'Chandpur', 'Faridganj'),
  ('3611', 'Chattogram', 'Chandpur', 'Hajiganj'),
  ('3610', 'Chattogram', 'Chandpur', 'Hajiganj'),
  ('3661', 'Chattogram', 'Chandpur', 'Hayemchar'),
  ('3660', 'Chattogram', 'Chandpur', 'Hayemchar'),
  ('3630', 'Chattogram', 'Chandpur', 'Kachua'),
  ('3631', 'Chattogram', 'Chandpur', 'Kachua'),
  ('3632', 'Chattogram', 'Chandpur', 'Kachua'),
  ('3633', 'Chattogram', 'Chandpur', 'Kachua'),
  ('3642', 'Chattogram', 'Chandpur', 'Matlobganj'),
  ('3640', 'Chattogram', 'Chandpur', 'Matlobganj'),
  ('3641', 'Chattogram', 'Chandpur', 'Matlobganj'),
  ('3623', 'Chattogram', 'Chandpur', 'Shahrasti'),
  ('3624', 'Chattogram', 'Chandpur', 'Shahrasti'),
  ('3621', 'Chattogram', 'Chandpur', 'Shahrasti'),
  ('3622', 'Chattogram', 'Chandpur', 'Shahrasti'),
  ('3620', 'Chattogram', 'Chandpur', 'Shahrasti'),
  ('4376', 'Chattogram', 'Chattogram', 'Anawara'),
  ('4378', 'Chattogram', 'Chattogram', 'Anawara'),
  ('4377', 'Chattogram', 'Chattogram', 'Anawara'),
  ('4366', 'Chattogram', 'Chattogram', 'Boalkhali'),
  ('4369', 'Chattogram', 'Chattogram', 'Boalkhali'),
  ('4365', 'Chattogram', 'Chattogram', 'Boalkhali'),
  ('4368', 'Chattogram', 'Chattogram', 'Boalkhali'),
  ('4363', 'Chattogram', 'Chattogram', 'Boalkhali'),
  ('4367', 'Chattogram', 'Chattogram', 'Boalkhali'),
  ('4364', 'Chattogram', 'Chattogram', 'Boalkhali'),
  ('4221', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4211', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4215', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4210', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4212', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4203', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4220', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4219', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4209', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4218', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4205', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4100', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4000', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4223', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4207', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4216', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4225', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4214', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4206', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4222', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4208', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4226', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4217', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4202', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4204', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4224', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4213', 'Chattogram', 'Chattogram', 'Chattogram Sadar'),
  ('4383', 'Chattogram', 'Chattogram', 'East Joara'),
  ('4382', 'Chattogram', 'Chattogram', 'East Joara'),
  ('4380', 'Chattogram', 'Chattogram', 'East Joara'),
  ('4381', 'Chattogram', 'Chattogram', 'East Joara');

INSERT INTO bd_postcodes (postcode, division_name, district_name, thana_name) VALUES
  ('4352', 'Chattogram', 'Chattogram', 'Fatikchhari'),
  ('4350', 'Chattogram', 'Chattogram', 'Fatikchhari'),
  ('4354', 'Chattogram', 'Chattogram', 'Fatikchhari'),
  ('4353', 'Chattogram', 'Chattogram', 'Fatikchhari'),
  ('4351', 'Chattogram', 'Chattogram', 'Fatikchhari'),
  ('4355', 'Chattogram', 'Chattogram', 'Fatikchhari'),
  ('4331', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4335', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4332', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4330', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4333', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4339', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4334', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4337', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4338', 'Chattogram', 'Chattogram', 'Hathazari'),
  ('4393', 'Chattogram', 'Chattogram', 'Jaldi'),
  ('4392', 'Chattogram', 'Chattogram', 'Jaldi'),
  ('4390', 'Chattogram', 'Chattogram', 'Jaldi'),
  ('4391', 'Chattogram', 'Chattogram', 'Jaldi'),
  ('4398', 'Chattogram', 'Chattogram', 'Lohagara'),
  ('4396', 'Chattogram', 'Chattogram', 'Lohagara'),
  ('4397', 'Chattogram', 'Chattogram', 'Lohagara'),
  ('4321', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4325', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4323', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4322', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4324', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4327', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4320', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4328', 'Chattogram', 'Chattogram', 'Mirsharai'),
  ('4371', 'Chattogram', 'Chattogram', 'Patiya'),
  ('4370', 'Chattogram', 'Chattogram', 'Patiya'),
  ('4361', 'Chattogram', 'Chattogram', 'Rangunia'),
  ('4360', 'Chattogram', 'Chattogram', 'Rangunia'),
  ('4349', 'Chattogram', 'Chattogram', 'Raozan'),
  ('4341', 'Chattogram', 'Chattogram', 'Raozan'),
  ('4347', 'Chattogram', 'Chattogram', 'Raozan'),
  ('4345', 'Chattogram', 'Chattogram', 'Raozan'),
  ('4343', 'Chattogram', 'Chattogram', 'Raozan'),
  ('4346', 'Chattogram', 'Chattogram', 'Rouzan'),
  ('4344', 'Chattogram', 'Chattogram', 'Rouzan'),
  ('4342', 'Chattogram', 'Chattogram', 'Rouzan'),
  ('4348', 'Chattogram', 'Chattogram', 'Rouzan'),
  ('4340', 'Chattogram', 'Chattogram', 'Rouzan'),
  ('4300', 'Chattogram', 'Chattogram', 'Sandwip'),
  ('4301', 'Chattogram', 'Chattogram', 'Sandwip'),
  ('4302', 'Chattogram', 'Chattogram', 'Sandwip'),
  ('4387', 'Chattogram', 'Chattogram', 'Satkania'),
  ('4388', 'Chattogram', 'Chattogram', 'Satkania'),
  ('4386', 'Chattogram', 'Chattogram', 'Satkania'),
  ('4312', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('4311', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('4313', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('4315', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('4316', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('4317', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('4314', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('4310', 'Chattogram', 'Chattogram', 'Sitakunda'),
  ('3560', 'Chattogram', 'Cumilla', 'Barura'),
  ('3562', 'Chattogram', 'Cumilla', 'Barura'),
  ('3561', 'Chattogram', 'Cumilla', 'Barura'),
  ('3526', 'Chattogram', 'Cumilla', 'Brahmanpara'),
  ('3520', 'Chattogram', 'Cumilla', 'Burichang'),
  ('3521', 'Chattogram', 'Cumilla', 'Burichang'),
  ('3510', 'Chattogram', 'Cumilla', 'Chandina'),
  ('3511', 'Chattogram', 'Cumilla', 'Chandina'),
  ('3551', 'Chattogram', 'Cumilla', 'Chouddagram'),
  ('3552', 'Chattogram', 'Cumilla', 'Chouddagram'),
  ('3550', 'Chattogram', 'Cumilla', 'Chouddagram'),
  ('3501', 'Chattogram', 'Cumilla', 'Comilla Sadar'),
  ('3500', 'Chattogram', 'Cumilla', 'Comilla Sadar'),
  ('3503', 'Chattogram', 'Cumilla', 'Comilla Sadar'),
  ('3502', 'Chattogram', 'Cumilla', 'Comilla Sadar'),
  ('3504', 'Chattogram', 'Cumilla', 'Comilla Sadar'),
  ('3518', 'Chattogram', 'Cumilla', 'Daudkandi'),
  ('3516', 'Chattogram', 'Cumilla', 'Daudkandi'),
  ('3519', 'Chattogram', 'Cumilla', 'Daudkandi'),
  ('3517', 'Chattogram', 'Cumilla', 'Daudkandi'),
  ('3532', 'Chattogram', 'Cumilla', 'Davidhar'),
  ('3530', 'Chattogram', 'Cumilla', 'Davidhar'),
  ('3533', 'Chattogram', 'Cumilla', 'Davidhar'),
  ('3531', 'Chattogram', 'Cumilla', 'Davidhar'),
  ('3546', 'Chattogram', 'Cumilla', 'Homna'),
  ('3572', 'Chattogram', 'Cumilla', 'Laksam'),
  ('3570', 'Chattogram', 'Cumilla', 'Laksam'),
  ('3571', 'Chattogram', 'Cumilla', 'Laksam'),
  ('3582', 'Chattogram', 'Cumilla', 'Langalkot'),
  ('3581', 'Chattogram', 'Cumilla', 'Langalkot'),
  ('3583', 'Chattogram', 'Cumilla', 'Langalkot'),
  ('3580', 'Chattogram', 'Cumilla', 'Langalkot'),
  ('3543', 'Chattogram', 'Cumilla', 'Muradnagar'),
  ('3542', 'Chattogram', 'Cumilla', 'Muradnagar'),
  ('3540', 'Chattogram', 'Cumilla', 'Muradnagar'),
  ('3545', 'Chattogram', 'Cumilla', 'Muradnagar'),
  ('3541', 'Chattogram', 'Cumilla', 'Muradnagar'),
  ('3544', 'Chattogram', 'Cumilla', 'Muradnagar'),
  ('4742', 'Chattogram', 'Cox''s Bazar', 'Chiringga'),
  ('4740', 'Chattogram', 'Cox''s Bazar', 'Chiringga'),
  ('4741', 'Chattogram', 'Cox''s Bazar', 'Chiringga'),
  ('4743', 'Chattogram', 'Cox''s Bazar', 'Chiringga'),
  ('4700', 'Chattogram', 'Cox''s Bazar', 'Coxs Bazar Sadar'),
  ('4702', 'Chattogram', 'Cox''s Bazar', 'Coxs Bazar Sadar'),
  ('4701', 'Chattogram', 'Cox''s Bazar', 'Coxs Bazar Sadar'),
  ('4710', 'Chattogram', 'Cox''s Bazar', 'Gorakghat'),
  ('4720', 'Chattogram', 'Cox''s Bazar', 'Kutubdia'),
  ('4730', 'Chattogram', 'Cox''s Bazar', 'Ramu'),
  ('4761', 'Chattogram', 'Cox''s Bazar', 'Teknaf'),
  ('4762', 'Chattogram', 'Cox''s Bazar', 'Teknaf'),
  ('4760', 'Chattogram', 'Cox''s Bazar', 'Teknaf'),
  ('4750', 'Chattogram', 'Cox''s Bazar', 'Ukhia'),
  ('3910', 'Chattogram', 'Feni', 'Chhagalnaia'),
  ('3912', 'Chattogram', 'Feni', 'Chhagalnaia'),
  ('3911', 'Chattogram', 'Feni', 'Chhagalnaia'),
  ('3913', 'Chattogram', 'Feni', 'Chhagalnaia'),
  ('3922', 'Chattogram', 'Feni', 'Dagonbhuia'),
  ('3920', 'Chattogram', 'Feni', 'Dagonbhuia'),
  ('3921', 'Chattogram', 'Feni', 'Dagonbhuia'),
  ('3923', 'Chattogram', 'Feni', 'Dagonbhuia'),
  ('3901', 'Chattogram', 'Feni', 'Feni Sadar'),
  ('3900', 'Chattogram', 'Feni', 'Feni Sadar'),
  ('3903', 'Chattogram', 'Feni', 'Feni Sadar'),
  ('3902', 'Chattogram', 'Feni', 'Feni Sadar'),
  ('3942', 'Chattogram', 'Feni', 'Pashurampur'),
  ('3943', 'Chattogram', 'Feni', 'Pashurampur'),
  ('3940', 'Chattogram', 'Feni', 'Pashurampur'),
  ('3941', 'Chattogram', 'Feni', 'Pashurampur'),
  ('3932', 'Chattogram', 'Feni', 'Sonagazi'),
  ('3933', 'Chattogram', 'Feni', 'Sonagazi'),
  ('3931', 'Chattogram', 'Feni', 'Sonagazi'),
  ('3930', 'Chattogram', 'Feni', 'Sonagazi'),
  ('4420', 'Chattogram', 'Khagrachari', 'Diginala'),
  ('4400', 'Chattogram', 'Khagrachari', 'Khagrachari Sadar'),
  ('4470', 'Chattogram', 'Khagrachari', 'Laxmichhari'),
  ('4430', 'Chattogram', 'Khagrachari', 'Mahalchhari'),
  ('4460', 'Chattogram', 'Khagrachari', 'Manikchhari'),
  ('4450', 'Chattogram', 'Khagrachari', 'Matiranga'),
  ('4410', 'Chattogram', 'Khagrachari', 'Panchhari'),
  ('4440', 'Chattogram', 'Khagrachari', 'Ramghar Head Office'),
  ('3730', 'Chattogram', 'Lakshmipur', 'Char Alexgander'),
  ('3731', 'Chattogram', 'Lakshmipur', 'Char Alexgander'),
  ('3732', 'Chattogram', 'Lakshmipur', 'Char Alexgander'),
  ('3709', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3702', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3708', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3707', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3701', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3706', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3704', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3700', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3703', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3705', 'Chattogram', 'Lakshmipur', 'Lakshimpur Sadar'),
  ('3721', 'Chattogram', 'Lakshmipur', 'Ramganj'),
  ('3725', 'Chattogram', 'Lakshmipur', 'Ramganj'),
  ('3723', 'Chattogram', 'Lakshmipur', 'Ramganj'),
  ('3724', 'Chattogram', 'Lakshmipur', 'Ramganj'),
  ('3722', 'Chattogram', 'Lakshmipur', 'Ramganj'),
  ('3720', 'Chattogram', 'Lakshmipur', 'Ramganj'),
  ('3714', 'Chattogram', 'Lakshmipur', 'Raypur'),
  ('3713', 'Chattogram', 'Lakshmipur', 'Raypur'),
  ('3712', 'Chattogram', 'Lakshmipur', 'Raypur'),
  ('3711', 'Chattogram', 'Lakshmipur', 'Raypur'),
  ('3710', 'Chattogram', 'Lakshmipur', 'Raypur'),
  ('3850', 'Chattogram', 'Noakhali', 'Basurhat'),
  ('3851', 'Chattogram', 'Noakhali', 'Basurhat'),
  ('3831', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3847', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3822', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3824', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3820', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3837', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3821', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3843', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3848', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3828', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3825', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3844', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3829', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3833', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3842', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3838', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3823', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3839', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3841', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3835', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3834', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3827', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3832', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3845', 'Chattogram', 'Noakhali', 'Begumganj'),
  ('3879', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3873', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3870', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3878', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3877', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3872', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3871', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3874', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3881', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3882', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3883', 'Chattogram', 'Noakhali', 'Chatkhil'),
  ('3875', 'Chattogram', 'Noakhali', 'Chatkhil');

INSERT INTO bd_postcodes (postcode, division_name, district_name, thana_name) VALUES
  ('3891', 'Chattogram', 'Noakhali', 'Hatiya'),
  ('3890', 'Chattogram', 'Noakhali', 'Hatiya'),
  ('3892', 'Chattogram', 'Noakhali', 'Hatiya'),
  ('3811', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3812', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3809', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3803', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3807', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3808', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3806', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3801', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3800', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3804', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3802', 'Chattogram', 'Noakhali', 'Noakhali Sadar'),
  ('3862', 'Chattogram', 'Noakhali', 'Senbag'),
  ('3864', 'Chattogram', 'Noakhali', 'Senbag'),
  ('3861', 'Chattogram', 'Noakhali', 'Senbag'),
  ('3863', 'Chattogram', 'Noakhali', 'Senbag'),
  ('3860', 'Chattogram', 'Noakhali', 'Senbag'),
  ('3865', 'Chattogram', 'Noakhali', 'Senbag'),
  ('4570', 'Chattogram', 'Rangamati', 'Barakal'),
  ('4550', 'Chattogram', 'Rangamati', 'Bilaichhari'),
  ('4560', 'Chattogram', 'Rangamati', 'Jarachhari'),
  ('4511', 'Chattogram', 'Rangamati', 'Kalampati'),
  ('4510', 'Chattogram', 'Rangamati', 'Kalampati'),
  ('4531', 'Chattogram', 'Rangamati', 'kaptai'),
  ('4530', 'Chattogram', 'Rangamati', 'kaptai'),
  ('4533', 'Chattogram', 'Rangamati', 'kaptai'),
  ('4532', 'Chattogram', 'Rangamati', 'kaptai'),
  ('4580', 'Chattogram', 'Rangamati', 'Longachh'),
  ('4590', 'Chattogram', 'Rangamati', 'Marishya'),
  ('4520', 'Chattogram', 'Rangamati', 'Naniachhar'),
  ('4540', 'Chattogram', 'Rangamati', 'Rajsthali'),
  ('4500', 'Chattogram', 'Rangamati', 'Rangamati Sadar'),
  ('5270', 'Rangpur', 'Dinajpur', 'Bangla Hili'),
  ('5210', 'Rangpur', 'Dinajpur', 'Biral'),
  ('5266', 'Rangpur', 'Dinajpur', 'Mohakhali'),
  ('5220', 'Rangpur', 'Dinajpur', 'Birganj'),
  ('5240', 'Rangpur', 'Dinajpur', 'Chirirbandar'),
  ('5241', 'Rangpur', 'Dinajpur', 'Chirirbandar'),
  ('5201', 'Rangpur', 'Dinajpur', 'Dinajpur Sadar'),
  ('5200', 'Rangpur', 'Dinajpur', 'Dinajpur Sadar'),
  ('5230', 'Rangpur', 'Dinajpur', 'Khansama'),
  ('5231', 'Rangpur', 'Dinajpur', 'Khansama'),
  ('5226', 'Rangpur', 'Dinajpur', 'Maharajganj'),
  ('5281', 'Rangpur', 'Dinajpur', 'Nawabganj'),
  ('5282', 'Rangpur', 'Dinajpur', 'Nawabganj'),
  ('5280', 'Rangpur', 'Dinajpur', 'Nawabganj'),
  ('5291', 'Rangpur', 'Dinajpur', 'Ghoraghat'),
  ('5290', 'Rangpur', 'Dinajpur', 'Ghoraghat'),
  ('5250', 'Rangpur', 'Dinajpur', 'Parbatipur'),
  ('5260', 'Rangpur', 'Dinajpur', 'Phulbari'),
  ('5216', 'Rangpur', 'Dinajpur', 'Setabganj'),
  ('5750', 'Rangpur', 'Gaibandha', 'Bonarpara'),
  ('5751', 'Rangpur', 'Gaibandha', 'Bonarpara'),
  ('5700', 'Rangpur', 'Gaibandha', 'Gaibandha Sadar'),
  ('5740', 'Rangpur', 'Gaibandha', 'Gobindaganj'),
  ('5741', 'Rangpur', 'Gaibandha', 'Gobindaganj'),
  ('5730', 'Rangpur', 'Gaibandha', 'Palashbari'),
  ('5761', 'Rangpur', 'Gaibandha', 'Phulchhari'),
  ('5760', 'Rangpur', 'Gaibandha', 'Phulchhari'),
  ('5711', 'Rangpur', 'Gaibandha', 'Saadullapur'),
  ('5710', 'Rangpur', 'Gaibandha', 'Saadullapur'),
  ('5721', 'Rangpur', 'Gaibandha', 'Sundarganj'),
  ('5720', 'Rangpur', 'Gaibandha', 'Sundarganj'),
  ('5670', 'Rangpur', 'Kurigram', 'Bhurungamari'),
  ('5630', 'Rangpur', 'Kurigram', 'Chilmari'),
  ('5631', 'Rangpur', 'Kurigram', 'Chilmari'),
  ('5600', 'Rangpur', 'Kurigram', 'Kurigram Sadar'),
  ('5601', 'Rangpur', 'Kurigram', 'Kurigram Sadar'),
  ('5680', 'Rangpur', 'Kurigram', 'Kurigram Sadar'),
  ('5660', 'Rangpur', 'Kurigram', 'Nageshwar'),
  ('5611', 'Rangpur', 'Kurigram', 'Rajarhat'),
  ('05610', 'Rangpur', 'Kurigram', 'Rajarhat'),
  ('5650', 'Rangpur', 'Kurigram', 'Rajibpur'),
  ('5640', 'Rangpur', 'Kurigram', 'Roumari'),
  ('5621', 'Rangpur', 'Kurigram', 'Ulipur'),
  ('5620', 'Rangpur', 'Kurigram', 'Ulipur'),
  ('5510', 'Rangpur', 'Lalmonirhat', 'Aditmari'),
  ('5530', 'Rangpur', 'Lalmonirhat', 'Hatibandha'),
  ('5502', 'Rangpur', 'Lalmonirhat', 'Lalmonirhat Sadar'),
  ('5500', 'Rangpur', 'Lalmonirhat', 'Lalmonirhat Sadar'),
  ('5501', 'Rangpur', 'Lalmonirhat', 'Lalmonirhat Sadar'),
  ('5541', 'Rangpur', 'Lalmonirhat', 'Patgram'),
  ('5542', 'Rangpur', 'Lalmonirhat', 'Patgram'),
  ('5540', 'Rangpur', 'Lalmonirhat', 'Patgram'),
  ('5520', 'Rangpur', 'Lalmonirhat', 'Tushbhandar'),
  ('5350', 'Rangpur', 'Nilphamari', 'Dimla'),
  ('5351', 'Rangpur', 'Nilphamari', 'Dimla'),
  ('5341', 'Rangpur', 'Nilphamari', 'Domar'),
  ('5340', 'Rangpur', 'Nilphamari', 'Domar'),
  ('5330', 'Rangpur', 'Nilphamari', 'Jaldhaka'),
  ('5320', 'Rangpur', 'Nilphamari', 'Kishoriganj'),
  ('5300', 'Rangpur', 'Nilphamari', 'Nilphamari Sadar'),
  ('5301', 'Rangpur', 'Nilphamari', 'Nilphamari Sadar'),
  ('5310', 'Rangpur', 'Nilphamari', 'Saidpur'),
  ('5311', 'Rangpur', 'Nilphamari', 'Saidpur'),
  ('5010', 'Rangpur', 'Panchagarh', 'Boda'),
  ('4050', 'Rangpur', 'Panchagarh', 'Chotto Dab'),
  ('5041', 'Rangpur', 'Panchagarh', 'Chotto Dab'),
  ('5020', 'Rangpur', 'Panchagarh', 'Dabiganj'),
  ('5000', 'Rangpur', 'Panchagarh', 'Panchagra Sadar'),
  ('5030', 'Rangpur', 'Panchagarh', 'Tetulia'),
  ('5420', 'Rangpur', 'Rangpur', 'Taraganj'),
  ('5431', 'Rangpur', 'Rangpur', 'Badarganj'),
  ('5410', 'Rangpur', 'Rangpur', 'Gangachara'),
  ('5441', 'Rangpur', 'Rangpur', 'Kaunia'),
  ('5440', 'Rangpur', 'Rangpur', 'Kaunia'),
  ('5450', 'Rangpur', 'Rangpur', 'Pirgachha'),
  ('5460', 'Rangpur', 'Rangpur', 'Mithapukur'),
  ('5470', 'Rangpur', 'Rangpur', 'Pirganj'),
  ('5402', 'Rangpur', 'Rangpur', 'Rangpur Sadar'),
  ('5403', 'Rangpur', 'Rangpur', 'Rangpur Sadar'),
  ('5404', 'Rangpur', 'Rangpur', 'Rangpur Sadar'),
  ('5405', 'Rangpur', 'Rangpur', 'Rangpur Sadar'),
  ('5400', 'Rangpur', 'Rangpur', 'Rangpur Sadar'),
  ('5401', 'Rangpur', 'Rangpur', 'Rangpur Sadar'),
  ('5430', 'Rangpur', 'Rangpur', 'Badarganj'),
  ('5140', 'Rangpur', 'Thakurgaon', 'Baliadangi'),
  ('5141', 'Rangpur', 'Thakurgaon', 'Baliadangi'),
  ('5130', 'Rangpur', 'Thakurgaon', 'Jibanpur'),
  ('5110', 'Rangpur', 'Thakurgaon', 'Pirganj'),
  ('5121', 'Rangpur', 'Thakurgaon', 'Rani Sankail'),
  ('5120', 'Rangpur', 'Thakurgaon', 'Rani Sankail'),
  ('5103', 'Rangpur', 'Thakurgaon', 'Thakurgaon Sadar'),
  ('5102', 'Rangpur', 'Thakurgaon', 'Thakurgaon Sadar'),
  ('5101', 'Rangpur', 'Thakurgaon', 'Thakurgaon Sadar'),
  ('5100', 'Rangpur', 'Thakurgaon', 'Thakurgaon Sadar'),
  ('5890', 'Rajshahi', 'Bogura', 'Adamdighi'),
  ('5892', 'Rajshahi', 'Bogura', 'Adamdighi'),
  ('5891', 'Rajshahi', 'Bogura', 'Adamdighi'),
  ('5801', 'Rajshahi', 'Bogura', 'Bogura Sadar'),
  ('5800', 'Rajshahi', 'Bogura', 'Bogura Sadar'),
  ('5850', 'Rajshahi', 'Bogura', 'Dhunat'),
  ('5851', 'Rajshahi', 'Bogura', 'Dhunat'),
  ('5880', 'Rajshahi', 'Bogura', 'Dupchanchia'),
  ('5881', 'Rajshahi', 'Bogura', 'Dupchachia'),
  ('5820', 'Rajshahi', 'Bogura', 'Gabtoli'),
  ('5821', 'Rajshahi', 'Bogura', 'Gabtoli'),
  ('5870', 'Rajshahi', 'Bogura', 'Kahalu'),
  ('5860', 'Rajshahi', 'Bogura', 'Nandigram'),
  ('5831', 'Rajshahi', 'Bogura', 'Sariakandi'),
  ('5830', 'Rajshahi', 'Bogura', 'Sariakandi'),
  ('5841', 'Rajshahi', 'Bogura', 'Sherpur'),
  ('5842', 'Rajshahi', 'Bogura', 'Sherpur'),
  ('5840', 'Rajshahi', 'Bogura', 'Sherpur'),
  ('5810', 'Rajshahi', 'Bogura', 'Shibganj'),
  ('5826', 'Rajshahi', 'Bogura', 'Sonatola'),
  ('6330', 'Rajshahi', 'Chapai Nawabganj', 'Bholahat'),
  ('6303', 'Rajshahi', 'Chapai Nawabganj', 'Chapai Nawabganj Sadar'),
  ('6300', 'Rajshahi', 'Chapai Nawabganj', 'Chapai Nawabganj Sadar'),
  ('6301', 'Rajshahi', 'Chapai Nawabganj', 'Chapai Nawabganj Sadar'),
  ('6302', 'Rajshahi', 'Chapai Nawabganj', 'Chapai Nawabganj Sadar'),
  ('6311', 'Rajshahi', 'Chapai Nawabganj', 'Nachol'),
  ('6310', 'Rajshahi', 'Chapai Nawabganj', 'Nachol'),
  ('6321', 'Rajshahi', 'Chapai Nawabganj', 'Rohanpur'),
  ('6320', 'Rajshahi', 'Chapai Nawabganj', 'Rohanpur'),
  ('6341', 'Rajshahi', 'Chapai Nawabganj', 'Shibganj U.P.O'),
  ('6342', 'Rajshahi', 'Chapai Nawabganj', 'Shibganj U.P.O'),
  ('6340', 'Rajshahi', 'Chapai Nawabganj', 'Shibganj U.P.O'),
  ('5940', 'Rajshahi', 'Joypurhat', 'Akkelpur'),
  ('5941', 'Rajshahi', 'Joypurhat', 'Akkelpur'),
  ('5942', 'Rajshahi', 'Joypurhat', 'Akkelpur'),
  ('5900', 'Rajshahi', 'Joypurhat', 'Joypurhat Sadar'),
  ('5930', 'Rajshahi', 'Joypurhat', 'kalai'),
  ('5920', 'Rajshahi', 'Joypurhat', 'Khetlal'),
  ('5910', 'Rajshahi', 'Joypurhat', 'panchbibi'),
  ('6596', 'Rajshahi', 'Naogaon', 'Ahsanganj'),
  ('6597', 'Rajshahi', 'Naogaon', 'Ahsanganj'),
  ('6570', 'Rajshahi', 'Naogaon', 'Badalgachhi'),
  ('6580', 'Rajshahi', 'Naogaon', 'Dhamuirhat'),
  ('6530', 'Rajshahi', 'Naogaon', 'Mahadebpur'),
  ('6500', 'Rajshahi', 'Naogaon', 'Naogaon Sadar'),
  ('6520', 'Rajshahi', 'Naogaon', 'Niamatpur'),
  ('6550', 'Rajshahi', 'Naogaon', 'Nitpur'),
  ('6552', 'Rajshahi', 'Naogaon', 'Nitpur'),
  ('6551', 'Rajshahi', 'Naogaon', 'Nitpur'),
  ('6540', 'Rajshahi', 'Naogaon', 'Patnitala'),
  ('6512', 'Rajshahi', 'Naogaon', 'Prasadpur'),
  ('6511', 'Rajshahi', 'Naogaon', 'Prasadpur'),
  ('6510', 'Rajshahi', 'Naogaon', 'Prasadpur'),
  ('6591', 'Rajshahi', 'Naogaon', 'Raninagar'),
  ('6590', 'Rajshahi', 'Naogaon', 'Raninagar'),
  ('6561', 'Rajshahi', 'Naogaon', 'Sapahar'),
  ('6560', 'Rajshahi', 'Naogaon', 'Sapahar'),
  ('6422', 'Rajshahi', 'Natore', 'Gopalpur UPO'),
  ('6420', 'Rajshahi', 'Natore', 'Gopalpur UPO'),
  ('6421', 'Rajshahi', 'Natore', 'Gopalpur UPO'),
  ('6432', 'Rajshahi', 'Natore', 'Harua'),
  ('6431', 'Rajshahi', 'Natore', 'Harua'),
  ('6430', 'Rajshahi', 'Natore', 'Harua'),
  ('6440', 'Rajshahi', 'Natore', 'Hatgurudaspur'),
  ('6410', 'Rajshahi', 'Natore', 'Laxman'),
  ('6402', 'Rajshahi', 'Natore', 'Natore Sadar'),
  ('6401', 'Rajshahi', 'Natore', 'Natore Sadar'),
  ('6403', 'Rajshahi', 'Natore', 'Natore Sadar'),
  ('6400', 'Rajshahi', 'Natore', 'Natore Sadar'),
  ('6450', 'Rajshahi', 'Natore', 'Singra'),
  ('6650', 'Rajshahi', 'Pabna', 'Banwarinagar'),
  ('6680', 'Rajshahi', 'Pabna', 'Bera');

INSERT INTO bd_postcodes (postcode, division_name, district_name, thana_name) VALUES
  ('6682', 'Rajshahi', 'Pabna', 'Bera'),
  ('6681', 'Rajshahi', 'Pabna', 'Bera'),
  ('6683', 'Rajshahi', 'Pabna', 'Bera'),
  ('6640', 'Rajshahi', 'Pabna', 'Bhangura'),
  ('6630', 'Rajshahi', 'Pabna', 'Chatmohar'),
  ('6610', 'Rajshahi', 'Pabna', 'Atghoria'),
  ('6621', 'Rajshahi', 'Pabna', 'Ishwardi'),
  ('6620', 'Rajshahi', 'Pabna', 'Ishwardi'),
  ('6622', 'Rajshahi', 'Pabna', 'Ishwardi'),
  ('6623', 'Rajshahi', 'Pabna', 'Ishwardi'),
  ('6602', 'Rajshahi', 'Pabna', 'Pabna Sadar'),
  ('6601', 'Rajshahi', 'Pabna', 'Pabna Sadar'),
  ('6600', 'Rajshahi', 'Pabna', 'Pabna Sadar'),
  ('6670', 'Rajshahi', 'Pabna', 'Sathia'),
  ('6661', 'Rajshahi', 'Pabna', 'Sujanagar'),
  ('6660', 'Rajshahi', 'Pabna', 'Sujanagar'),
  ('6281', 'Rajshahi', 'Rajshahi', 'Bagha'),
  ('6280', 'Rajshahi', 'Rajshahi', 'Bagha'),
  ('6250', 'Rajshahi', 'Rajshahi', 'Bagmara'),
  ('6251', 'Rajshahi', 'Rajshahi', 'Bagmara'),
  ('6270', 'Rajshahi', 'Rajshahi', 'Charghat'),
  ('6271', 'Rajshahi', 'Rajshahi', 'Charghat'),
  ('6240', 'Rajshahi', 'Rajshahi', 'Durgapur'),
  ('6290', 'Rajshahi', 'Rajshahi', 'Godagari'),
  ('6291', 'Rajshahi', 'Rajshahi', 'Godagari'),
  ('6220', 'Rajshahi', 'Rajshahi', 'Khod Mohanpur'),
  ('6210', 'Rajshahi', 'Rajshahi', 'Lalitganj'),
  ('6211', 'Rajshahi', 'Rajshahi', 'Lalitganj'),
  ('6212', 'Rajshahi', 'Rajshahi', 'Lalitganj'),
  ('6260', 'Rajshahi', 'Rajshahi', 'Putia'),
  ('6206', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6100', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6204', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6202', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6201', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6000', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6205', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6203', 'Rajshahi', 'Rajshahi', 'Rajshahi Sadar'),
  ('6230', 'Rajshahi', 'Rajshahi', 'Tanor'),
  ('6730', 'Rajshahi', 'Sirajganj', 'Baiddya Jam Toil'),
  ('6740', 'Rajshahi', 'Sirajganj', 'Belkuchi'),
  ('6751', 'Rajshahi', 'Sirajganj', 'Belkuchi'),
  ('6742', 'Rajshahi', 'Sirajganj', 'Belkuchi'),
  ('6741', 'Rajshahi', 'Sirajganj', 'Belkuchi'),
  ('6752', 'Rajshahi', 'Sirajganj', 'Belkuchi'),
  ('6720', 'Rajshahi', 'Sirajganj', 'Dhangora'),
  ('6721', 'Rajshahi', 'Sirajganj', 'Dhangora'),
  ('6712', 'Rajshahi', 'Sirajganj', 'Kazipur'),
  ('6710', 'Rajshahi', 'Sirajganj', 'Kazipur'),
  ('6711', 'Rajshahi', 'Sirajganj', 'Kazipur'),
  ('6772', 'Rajshahi', 'Sirajganj', 'Shahjadpur'),
  ('6773', 'Rajshahi', 'Sirajganj', 'Shahjadpur'),
  ('6771', 'Rajshahi', 'Sirajganj', 'Shahjadpur'),
  ('6770', 'Rajshahi', 'Sirajganj', 'Shahjadpur'),
  ('6701', 'Rajshahi', 'Sirajganj', 'Sirajganj Sadar'),
  ('6702', 'Rajshahi', 'Sirajganj', 'Sirajganj Sadar'),
  ('6700', 'Rajshahi', 'Sirajganj', 'Sirajganj Sadar'),
  ('6780', 'Rajshahi', 'Sirajganj', 'Tarash'),
  ('6762', 'Rajshahi', 'Sirajganj', 'Ullapara'),
  ('6763', 'Rajshahi', 'Sirajganj', 'Ullapara'),
  ('6760', 'Rajshahi', 'Sirajganj', 'Ullapara'),
  ('6761', 'Rajshahi', 'Sirajganj', 'Ullapara'),
  ('8710', 'Barishal', 'Barguna', 'Amtali'),
  ('8730', 'Barishal', 'Barguna', 'Bamna'),
  ('8700', 'Barishal', 'Barguna', 'Barguna Sadar'),
  ('8701', 'Barishal', 'Barguna', 'Barguna Sadar'),
  ('8740', 'Barishal', 'Barguna', 'Betagi'),
  ('8741', 'Barishal', 'Barguna', 'Betagi'),
  ('8721', 'Barishal', 'Barguna', 'Patharghata'),
  ('8720', 'Barishal', 'Barguna', 'Patharghata'),
  ('8240', 'Barishal', 'Barishal', 'Agailzhara'),
  ('8241', 'Barishal', 'Barishal', 'Agailzhara'),
  ('8242', 'Barishal', 'Barishal', 'Agailzhara'),
  ('8210', 'Barishal', 'Barishal', 'Babuganj'),
  ('8216', 'Barishal', 'Barishal', 'Babuganj'),
  ('8212', 'Barishal', 'Barishal', 'Babuganj'),
  ('8213', 'Barishal', 'Barishal', 'Babuganj'),
  ('8215', 'Barishal', 'Barishal', 'Babuganj'),
  ('8211', 'Barishal', 'Barishal', 'Babuganj'),
  ('8214', 'Barishal', 'Barishal', 'Babuganj'),
  ('8260', 'Barishal', 'Barishal', 'Barajalia'),
  ('8261', 'Barishal', 'Barishal', 'Barajalia'),
  ('8200', 'Barishal', 'Barishal', 'Barishal Sadar'),
  ('8201', 'Barishal', 'Barishal', 'Barishal Sadar'),
  ('8206', 'Barishal', 'Barishal', 'Barishal Sadar'),
  ('8205', 'Barishal', 'Barishal', 'Barishal Sadar'),
  ('8204', 'Barishal', 'Barishal', 'Barishal Sadar'),
  ('8202', 'Barishal', 'Barishal', 'Barishal Sadar'),
  ('8203', 'Barishal', 'Barishal', 'Barishal Sadar'),
  ('8233', 'Barishal', 'Barishal', 'Gouranadi'),
  ('8230', 'Barishal', 'Barishal', 'Gouranadi'),
  ('8232', 'Barishal', 'Barishal', 'Gouranadi'),
  ('8231', 'Barishal', 'Barishal', 'Gouranadi'),
  ('8274', 'Barishal', 'Barishal', 'Mahendiganj'),
  ('8271', 'Barishal', 'Barishal', 'Mahendiganj'),
  ('8270', 'Barishal', 'Barishal', 'Mahendiganj'),
  ('8273', 'Barishal', 'Barishal', 'Mahendiganj'),
  ('8272', 'Barishal', 'Barishal', 'Mahendiganj'),
  ('8252', 'Barishal', 'Barishal', 'Muladi'),
  ('8251', 'Barishal', 'Barishal', 'Muladi'),
  ('8250', 'Barishal', 'Barishal', 'Muladi'),
  ('8281', 'Barishal', 'Barishal', 'Bakerganj'),
  ('8284', 'Barishal', 'Barishal', 'Bakerganj'),
  ('8282', 'Barishal', 'Barishal', 'Bakerganj'),
  ('8280', 'Barishal', 'Barishal', 'Bakerganj'),
  ('8283', 'Barishal', 'Barishal', 'Bakerganj'),
  ('8223', 'Barishal', 'Barishal', 'Uzirpur'),
  ('8221', 'Barishal', 'Barishal', 'Uzirpur'),
  ('8222', 'Barishal', 'Barishal', 'Uzirpur'),
  ('8224', 'Barishal', 'Barishal', 'Uzirpur'),
  ('8220', 'Barishal', 'Barishal', 'Uzirpur'),
  ('8300', 'Barishal', 'Bhola', 'Bhola Sadar'),
  ('8301', 'Barishal', 'Bhola', 'Bhola Sadar'),
  ('8320', 'Barishal', 'Bhola', 'Borhanuddin UPO'),
  ('8321', 'Barishal', 'Bhola', 'Borhanuddin UPO'),
  ('8340', 'Barishal', 'Bhola', 'Charfashion'),
  ('8341', 'Barishal', 'Bhola', 'Charfashion'),
  ('8342', 'Barishal', 'Bhola', 'Charfashion'),
  ('8310', 'Barishal', 'Bhola', 'Doulatkhan'),
  ('8311', 'Barishal', 'Bhola', 'Doulatkhan'),
  ('8360', 'Barishal', 'Bhola', 'Hajirhat'),
  ('8350', 'Barishal', 'Bhola', 'Hatshoshiganj'),
  ('8331', 'Barishal', 'Bhola', 'Lalmohan UPO'),
  ('8332', 'Barishal', 'Bhola', 'Lalmohan UPO'),
  ('8330', 'Barishal', 'Bhola', 'Lalmohan UPO'),
  ('8402', 'Barishal', 'Jhalokati', 'Jhalokati Sadar'),
  ('8403', 'Barishal', 'Jhalokati', 'Jhalokati Sadar'),
  ('8400', 'Barishal', 'Jhalokati', 'Jhalokati Sadar'),
  ('8401', 'Barishal', 'Jhalokati', 'Jhalokati Sadar'),
  ('8404', 'Barishal', 'Jhalokati', 'Jhalokati Sadar'),
  ('8431', 'Barishal', 'Jhalokati', 'Kathalia'),
  ('8430', 'Barishal', 'Jhalokati', 'Kathalia'),
  ('8432', 'Barishal', 'Jhalokati', 'Kathalia'),
  ('8433', 'Barishal', 'Jhalokati', 'Kathalia'),
  ('8421', 'Barishal', 'Jhalokati', 'Nalchhiti'),
  ('8420', 'Barishal', 'Jhalokati', 'Nalchhiti'),
  ('8410', 'Barishal', 'Jhalokati', 'Rajapur'),
  ('8621', 'Barishal', 'Patuakhali', 'Bauphal'),
  ('8620', 'Barishal', 'Patuakhali', 'Bauphal'),
  ('8622', 'Barishal', 'Patuakhali', 'Bauphal'),
  ('8624', 'Barishal', 'Patuakhali', 'Bauphal'),
  ('8623', 'Barishal', 'Patuakhali', 'Bauphal'),
  ('8630', 'Barishal', 'Patuakhali', 'Dashmina'),
  ('8640', 'Barishal', 'Patuakhali', 'Galachipa'),
  ('8641', 'Barishal', 'Patuakhali', 'Galachipa'),
  ('8650', 'Barishal', 'Patuakhali', 'Khepupara'),
  ('8651', 'Barishal', 'Patuakhali', 'Khepupara'),
  ('8602', 'Barishal', 'Patuakhali', 'Patuakhali Sadar'),
  ('8601', 'Barishal', 'Patuakhali', 'Patuakhali Sadar'),
  ('8600', 'Barishal', 'Patuakhali', 'Patuakhali Sadar'),
  ('8603', 'Barishal', 'Patuakhali', 'Patuakhali Sadar'),
  ('8610', 'Barishal', 'Patuakhali', 'Subidkhali'),
  ('8530', 'Barishal', 'Pirojpur', 'Banaripara'),
  ('8531', 'Barishal', 'Pirojpur', 'Banaripara'),
  ('8550', 'Barishal', 'Pirojpur', 'Bhandaria'),
  ('8552', 'Barishal', 'Pirojpur', 'Bhandaria'),
  ('8551', 'Barishal', 'Pirojpur', 'Bhandaria'),
  ('8513', 'Barishal', 'Pirojpur', 'kaukhali'),
  ('8512', 'Barishal', 'Pirojpur', 'kaukhali'),
  ('8510', 'Barishal', 'Pirojpur', 'kaukhali'),
  ('8511', 'Barishal', 'Pirojpur', 'kaukhali'),
  ('8565', 'Barishal', 'Pirojpur', 'Mathbaria'),
  ('8563', 'Barishal', 'Pirojpur', 'Mathbaria'),
  ('8562', 'Barishal', 'Pirojpur', 'Mathbaria'),
  ('8560', 'Barishal', 'Pirojpur', 'Mathbaria'),
  ('8566', 'Barishal', 'Pirojpur', 'Mathbaria'),
  ('8564', 'Barishal', 'Pirojpur', 'Mathbaria'),
  ('8561', 'Barishal', 'Pirojpur', 'Mathbaria'),
  ('8540', 'Barishal', 'Pirojpur', 'Nazirpur'),
  ('8541', 'Barishal', 'Pirojpur', 'Nazirpur'),
  ('8501', 'Barishal', 'Pirojpur', 'Pirojpur Sadar'),
  ('8502', 'Barishal', 'Pirojpur', 'Pirojpur Sadar'),
  ('8500', 'Barishal', 'Pirojpur', 'Pirojpur Sadar'),
  ('8521', 'Barishal', 'Pirojpur', 'Swarupkathi'),
  ('8523', 'Barishal', 'Pirojpur', 'Swarupkathi'),
  ('8522', 'Barishal', 'Pirojpur', 'Swarupkathi'),
  ('8520', 'Barishal', 'Pirojpur', 'Swarupkathi'),
  ('9300', 'Khulna', 'Bagerhat', 'Bagerhat Sadar'),
  ('9301', 'Khulna', 'Bagerhat', 'Bagerhat Sadar'),
  ('9302', 'Khulna', 'Bagerhat', 'Bagerhat Sadar'),
  ('9350', 'Khulna', 'Bagerhat', 'Chalna Ankorage'),
  ('9351', 'Khulna', 'Bagerhat', 'Chalna Ankorage'),
  ('9361', 'Khulna', 'Bagerhat', 'Chitalmari'),
  ('9360', 'Khulna', 'Bagerhat', 'Chitalmari'),
  ('9372', 'Khulna', 'Bagerhat', 'Fakirhat'),
  ('9370', 'Khulna', 'Bagerhat', 'Fakirhat'),
  ('9371', 'Khulna', 'Bagerhat', 'Fakirhat'),
  ('9310', 'Khulna', 'Bagerhat', 'Kachua UPO'),
  ('9311', 'Khulna', 'Bagerhat', 'Kachua UPO'),
  ('9383', 'Khulna', 'Bagerhat', 'Mollahat'),
  ('9382', 'Khulna', 'Bagerhat', 'Mollahat'),
  ('9381', 'Khulna', 'Bagerhat', 'Mollahat'),
  ('9380', 'Khulna', 'Bagerhat', 'Mollahat'),
  ('9384', 'Khulna', 'Bagerhat', 'Mollahat'),
  ('9385', 'Khulna', 'Bagerhat', 'Mollahat'),
  ('9320', 'Khulna', 'Bagerhat', 'Morelganj'),
  ('9321', 'Khulna', 'Bagerhat', 'Morelganj'),
  ('9322', 'Khulna', 'Bagerhat', 'Morelganj'),
  ('9341', 'Khulna', 'Bagerhat', 'Rampal'),
  ('9343', 'Khulna', 'Bagerhat', 'Rampal');

INSERT INTO bd_postcodes (postcode, division_name, district_name, thana_name) VALUES
  ('9340', 'Khulna', 'Bagerhat', 'Rampal'),
  ('9342', 'Khulna', 'Bagerhat', 'Rampal'),
  ('9330', 'Khulna', 'Bagerhat', 'Rayenda'),
  ('7210', 'Khulna', 'Chuadanga', 'Alamdanga'),
  ('7211', 'Khulna', 'Chuadanga', 'Alamdanga'),
  ('7200', 'Khulna', 'Chuadanga', 'Chuadanga Sadar'),
  ('7201', 'Khulna', 'Chuadanga', 'Chuadanga Sadar'),
  ('7222', 'Khulna', 'Chuadanga', 'Damurhuda'),
  ('7220', 'Khulna', 'Chuadanga', 'Damurhuda'),
  ('7221', 'Khulna', 'Chuadanga', 'Damurhuda'),
  ('7230', 'Khulna', 'Chuadanga', 'Doulatganj'),
  ('7470', 'Khulna', 'Jashore', 'Bagharpara'),
  ('7471', 'Khulna', 'Jashore', 'Bagharpara'),
  ('7410', 'Khulna', 'Jashore', 'Chaugachha'),
  ('7406', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7402', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7407', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7404', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7403', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7400', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7401', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7405', 'Khulna', 'Jashore', 'Jashore Sadar'),
  ('7420', 'Khulna', 'Jashore', 'Jhikargachha'),
  ('7450', 'Khulna', 'Jashore', 'Keshabpur'),
  ('7440', 'Khulna', 'Jashore', 'Monirampur'),
  ('7462', 'Khulna', 'Jashore', 'Noapara'),
  ('7460', 'Khulna', 'Jashore', 'Noapara'),
  ('7461', 'Khulna', 'Jashore', 'Noapara'),
  ('7433', 'Khulna', 'Jashore', 'Sarsa'),
  ('7431', 'Khulna', 'Jashore', 'Sarsa'),
  ('7432', 'Khulna', 'Jashore', 'Sarsa'),
  ('7430', 'Khulna', 'Jashore', 'Sarsa'),
  ('7310', 'Khulna', 'Jhenaidah', 'Harinakundu'),
  ('7301', 'Khulna', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('7300', 'Khulna', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('7330', 'Khulna', 'Jhenaidah', 'Kotchandpur'),
  ('7340', 'Khulna', 'Jhenaidah', 'Maheshpur'),
  ('7351', 'Khulna', 'Jhenaidah', 'Naldanga'),
  ('7350', 'Khulna', 'Jhenaidah', 'Naldanga'),
  ('7321', 'Khulna', 'Jhenaidah', 'Shailakupa'),
  ('7320', 'Khulna', 'Jhenaidah', 'Shailakupa'),
  ('9240', 'Khulna', 'Khulna', 'Alaipur'),
  ('9242', 'Khulna', 'Khulna', 'Alaipur'),
  ('9241', 'Khulna', 'Khulna', 'Alaipur'),
  ('9260', 'Khulna', 'Khulna', 'Batiaghat'),
  ('9261', 'Khulna', 'Khulna', 'Batiaghat'),
  ('9272', 'Khulna', 'Khulna', 'Chalna Bazar'),
  ('9270', 'Khulna', 'Khulna', 'Chalna Bazar'),
  ('9271', 'Khulna', 'Khulna', 'Chalna Bazar'),
  ('9273', 'Khulna', 'Khulna', 'Chalna Bazar'),
  ('9221', 'Khulna', 'Khulna', 'Digalia'),
  ('9220', 'Khulna', 'Khulna', 'Digalia'),
  ('9224', 'Khulna', 'Khulna', 'Digalia'),
  ('9223', 'Khulna', 'Khulna', 'Digalia'),
  ('9222', 'Khulna', 'Khulna', 'Digalia'),
  ('9207', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9203', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9202', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9205', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9100', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9000', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9201', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9208', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9204', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9206', 'Khulna', 'Khulna', 'Khulna Sadar'),
  ('9291', 'Khulna', 'Khulna', 'Koyra'),
  ('9290', 'Khulna', 'Khulna', 'Koyra'),
  ('9284', 'Khulna', 'Khulna', 'Paikgachha'),
  ('9285', 'Khulna', 'Khulna', 'Paikgachha'),
  ('9281', 'Khulna', 'Khulna', 'Paikgachha'),
  ('9282', 'Khulna', 'Khulna', 'Paikgachha'),
  ('9283', 'Khulna', 'Khulna', 'Paikgachha'),
  ('9280', 'Khulna', 'Khulna', 'Paikgachha'),
  ('9210', 'Khulna', 'Khulna', 'Phultala'),
  ('9252', 'Khulna', 'Khulna', 'Sajiara'),
  ('9251', 'Khulna', 'Khulna', 'Sajiara'),
  ('9250', 'Khulna', 'Khulna', 'Sajiara'),
  ('9253', 'Khulna', 'Khulna', 'Sajiara'),
  ('9231', 'Khulna', 'Khulna', 'Terakhada'),
  ('9230', 'Khulna', 'Khulna', 'Terakhada'),
  ('7042', 'Khulna', 'Kushtia', 'Bheramara'),
  ('7040', 'Khulna', 'Kushtia', 'Bheramara'),
  ('7041', 'Khulna', 'Kushtia', 'Bheramara'),
  ('7020', 'Khulna', 'Kushtia', 'Janipur'),
  ('7021', 'Khulna', 'Kushtia', 'Janipur'),
  ('7010', 'Khulna', 'Kushtia', 'Kumarkhali'),
  ('7011', 'Khulna', 'Kushtia', 'Kumarkhali'),
  ('7003', 'Khulna', 'Kushtia', 'Kushtia Sadar'),
  ('7002', 'Khulna', 'Kushtia', 'Kushtia Sadar'),
  ('7001', 'Khulna', 'Kushtia', 'Kushtia Sadar'),
  ('7000', 'Khulna', 'Kushtia', 'Kushtia Sadar'),
  ('7032', 'Khulna', 'Kushtia', 'Mirpur'),
  ('7030', 'Khulna', 'Kushtia', 'Mirpur'),
  ('7031', 'Khulna', 'Kushtia', 'Mirpur'),
  ('7052', 'Khulna', 'Kushtia', 'Rafayetpur'),
  ('7050', 'Khulna', 'Kushtia', 'Rafayetpur'),
  ('7051', 'Khulna', 'Kushtia', 'Rafayetpur'),
  ('7620', 'Khulna', 'Magura', 'Arpara'),
  ('7600', 'Khulna', 'Magura', 'Magura Sadar'),
  ('7631', 'Khulna', 'Magura', 'Mohammadpur'),
  ('7630', 'Khulna', 'Magura', 'Mohammadpur'),
  ('7632', 'Khulna', 'Magura', 'Mohammadpur'),
  ('7611', 'Khulna', 'Magura', 'Shripur'),
  ('7612', 'Khulna', 'Magura', 'Shripur'),
  ('7610', 'Khulna', 'Magura', 'Shripur'),
  ('7110', 'Khulna', 'Meherpur', 'Gangni'),
  ('7101', 'Khulna', 'Meherpur', 'Meherpur Sadar'),
  ('7152', 'Khulna', 'Meherpur', 'Meherpur Sadar'),
  ('7100', 'Khulna', 'Meherpur', 'Meherpur Sadar'),
  ('7102', 'Khulna', 'Meherpur', 'Meherpur Sadar'),
  ('7520', 'Khulna', 'Narail', 'Kalia'),
  ('7514', 'Khulna', 'Narail', 'Laxmipasha'),
  ('7512', 'Khulna', 'Narail', 'Laxmipasha'),
  ('7510', 'Khulna', 'Narail', 'Laxmipasha'),
  ('7511', 'Khulna', 'Narail', 'Laxmipasha'),
  ('7513', 'Khulna', 'Narail', 'Laxmipasha'),
  ('7521', 'Khulna', 'Narail', 'Mohajan'),
  ('7500', 'Khulna', 'Narail', 'Narail Sadar'),
  ('7501', 'Khulna', 'Narail', 'Narail Sadar'),
  ('9460', 'Khulna', 'Satkhira', 'Ashashuni'),
  ('9461', 'Khulna', 'Satkhira', 'Ashashuni'),
  ('9430', 'Khulna', 'Satkhira', 'Debbhata'),
  ('9431', 'Khulna', 'Satkhira', 'Debbhata'),
  ('9415', 'Khulna', 'Satkhira', 'kalaroa'),
  ('9413', 'Khulna', 'Satkhira', 'kalaroa'),
  ('9412', 'Khulna', 'Satkhira', 'kalaroa'),
  ('9410', 'Khulna', 'Satkhira', 'kalaroa'),
  ('9414', 'Khulna', 'Satkhira', 'kalaroa'),
  ('9440', 'Khulna', 'Satkhira', 'Kaliganj UPO'),
  ('9441', 'Khulna', 'Satkhira', 'Kaliganj UPO'),
  ('9442', 'Khulna', 'Satkhira', 'Kaliganj UPO'),
  ('9453', 'Khulna', 'Satkhira', 'Nakipur'),
  ('9454', 'Khulna', 'Satkhira', 'Nakipur'),
  ('9455', 'Khulna', 'Satkhira', 'Nakipur'),
  ('9450', 'Khulna', 'Satkhira', 'Nakipur'),
  ('9452', 'Khulna', 'Satkhira', 'Nakipur'),
  ('9451', 'Khulna', 'Satkhira', 'Nakipur'),
  ('9403', 'Khulna', 'Satkhira', 'Satkhira Sadar'),
  ('9402', 'Khulna', 'Satkhira', 'Satkhira Sadar'),
  ('9401', 'Khulna', 'Satkhira', 'Satkhira Sadar'),
  ('9400', 'Khulna', 'Satkhira', 'Satkhira Sadar'),
  ('9421', 'Khulna', 'Satkhira', 'Taala'),
  ('9420', 'Khulna', 'Satkhira', 'Taala'),
  ('1360', '', '', ''),
  ('1362', '', '', ''),
  ('1361', '', '', ''),
  ('1351', '', '', ''),
  ('1232', '', '', ''),
  ('1330', '', '', ''),
  ('1230|', '', '', ''),
  ('7804|', '', '', ''),
  ('1742|', '', '', ''),
  ('8120|', '', '', ''),
  ('2316|', '', '', ''),
  ('7910|', '', '', ''),
  ('1820|', '', '', ''),
  ('1520|', '', '', ''),
  ('1430|', '', '', ''),
  ('1620|', '', '', ''),
  ('7700|', '', '', ''),
  ('8000|', '', '', ''),
  ('2031', '', '', ''),
  ('2411|', '', '', ''),
  ('4600', '', '', ''),
  ('9411', '', '', ''),
  ('5610', '', '', ''),
  ('5040', '', '', '');
